const $=id=>document.getElementById(id);let currentPlan=null,selectedPresetKey='';
const presets={biblical:{label:'Bíblico',tone:'cinematic',music:'epic-ancient'},mysteries:{label:'Mistério',tone:'dramatic',music:'mystery-tension'},ancient:{label:'História antiga',tone:'documentary',music:'epic-ancient'},'life-lessons':{label:'Lição de vida',tone:'cinematic',music:'emotional-ambient'}};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function msg(t,e=false){const m=$('message');m.hidden=!t;m.textContent=t;m.style.color=e?'#ffb4b4':''}
function badge(r){if(r.status!=='completed')return['Processando','warn'];if(r.conclusion==='success')return['Concluído','ok'];if(r.conclusion==='cancelled')return['Cancelado','bad'];return['Falhou','bad']}
async function status(){try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha no status');$('quotaText').textContent=`${d.usedToday}/${d.dailyLimit||10} usados • ${d.remaining} restantes`;if($('generateBtn'))$('generateBtn').disabled=d.remaining<=0||!currentPlan;$('runs').innerHTML=(d.runs||[]).map(x=>{const[b,c]=badge(x),p=Math.max(0,Math.min(100,Number(x.progress??0))),dl=x.downloadUrl?`<a class="download" href="${x.downloadUrl}" target="_blank">Baixar MP4</a>`:'';return `<div class="run"><div><div class="run-title">${esc(x.name)}</div><span class="badge ${c}">${b}</span><div class="progress-wrap"><div class="progress-head"><span>${esc(x.stage||b)}</span><strong>${p}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div></div></div>${dl}</div>`}).join('')||'<p class="muted">Nenhum render ainda.</p>'}catch(e){$('quotaText').textContent='indisponível';$('runs').innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
function applyPreset(k){const p=presets[k];if(!p)return;selectedPresetKey=k;$('tone').value=p.tone;$('music').value=p.music;document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===k));$('presetStatus').textContent=`${p.label} selecionado. Escreva um tema ou deixe a IA escolher.`}
function renderPlan(p){currentPlan=p;if(!$('topic').value.trim())$('topic').value=p.title||'';$('planTitle').textContent=p.title||'Storyboard';$('planSummary').textContent=p.summary||'';$('sceneEditor').innerHTML=p.scenes.map((s,i)=>`<article class="scene" data-i="${i}"><div class="scene-head"><span class="scene-number">${i+1}</span><div class="scene-title">${esc(s.beat||`Cena ${i+1}`)}</div><span class="badge">desenho</span></div><div class="scene-grid"><div><label>Fala</label><textarea class="n">${esc(s.narration||'')}</textarea></div><div><label>Ilustração</label><textarea class="v">${esc(s.visual_description||'')}</textarea></div></div><input class="q" type="hidden" value="${esc(s.visual_query||'cartoon scene')}"></article>`).join('');$('planSection').hidden=false;$('planSection').scrollIntoView({behavior:'smooth'});status()}
function collect(){const p=JSON.parse(JSON.stringify(currentPlan));document.querySelectorAll('.scene').forEach((el,i)=>{p.scenes[i].narration=el.querySelector('.n').value.trim();p.scenes[i].visual_description=el.querySelector('.v').value.trim();p.scenes[i].visual_query=el.querySelector('.q').value.trim()||'cartoon scene';p.scenes[i].recommended_media='image'});return p}
async function plan(auto=false){const topic=$('topic').value.trim();if(!topic&&!selectedPresetKey)return msg('Escreva o tema ou escolha um nicho.',true);$('planBtn').disabled=true;msg('Criando roteiro e storyboard em desenho…');try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,presetKey:selectedPresetKey,duration:Number($('duration').value),tone:$('tone').value,visualStyle:'cartoon',cartoonStyle:$('cartoonStyle').value,mediaMode:'photos',references:[]})}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao criar roteiro');renderPlan(d.plan);msg('Storyboard pronto. Revise e só depois gere o MP4.')}catch(e){msg(e.message,true)}finally{$('planBtn').disabled=false}}
document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',()=>{applyPreset(b.dataset.preset);plan(true)}));$('planBtn').addEventListener('click',()=>plan(false));$('refreshBtn').addEventListener('click',status);$('music').addEventListener('change',()=>$('musicVolumeWrap').hidden=$('music').value==='off');
$('generateBtn').addEventListener('click',async()=>{if(!currentPlan)return msg('Crie o storyboard primeiro.',true);const p=collect();if(p.scenes.some(s=>!s.narration))return msg('Existe cena sem fala.',true);$('generateBtn').disabled=true;msg('Enviando Turbo v2 para renderização…');try{const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:$('topic').value.trim()||p.title,presetKey:selectedPresetKey,plan:p,duration:Number($('duration').value),tone:$('tone').value,visualStyle:'cartoon',cartoonStyle:$('cartoonStyle').value,mediaMode:'photos',captions:$('captions').value,music:$('music').value,musicVolume:$('musicVolume').value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao iniciar');msg('Turbo v2 iniciado. Acompanhe o progresso abaixo.');await status();setTimeout(status,3500)}catch(e){msg(e.message,true);$('generateBtn').disabled=false}});
setInterval(status,12000);setTimeout(status,1200);
