const $=id=>document.getElementById(id);let currentPlan=null,selectedPresetKey='',currentStep=1;
const presets={biblical:{label:'Histórias Bíblicas',tone:'cinematic',music:'epic-ancient'},devotional:{label:'Devocional Bíblico',tone:'cinematic',music:'emotional-ambient'},mysteries:{label:'Mistérios',tone:'dramatic',music:'mystery-tension'},ancient:{label:'História Antiga',tone:'documentary',music:'epic-ancient'},'life-lessons':{label:'Lição de Vida',tone:'cinematic',music:'emotional-ambient'},motivation:{label:'Motivacional',tone:'energetic',music:'viral-pulse'},science:{label:'Ciência e Espaço',tone:'documentary',music:'cinematic-rise'},'true-stories':{label:'Histórias Reais',tone:'documentary',music:'cinematic-rise'},animals:{label:'Natureza e Animais',tone:'documentary',music:'emotional-ambient'}};
const previewThemes={
  default:{caption:'Uma história que prende sua atenção até o fim.',cartoon:'cinematic vertical storytelling scene, expressive character, detailed background'},
  biblical:{caption:'Deus transforma histórias impossíveis em testemunhos de fé.',cartoon:'ancient biblical Middle East scene, authentic tunics, desert landscape, cinematic 2D illustration'},
  devotional:{caption:'Mesmo nos dias difíceis, a Palavra continua trazendo direção.',cartoon:'open bible, warm peaceful light, prayerful atmosphere, respectful Christian devotional 2D illustration'},
  mysteries:{caption:'O detalhe que parecia insignificante mudou toda a investigação.',cartoon:'mysterious foggy location, investigation clues, cinematic suspense 2D illustration'},
  ancient:{caption:'Civilizações antigas deixaram marcas que ainda impressionam o mundo.',cartoon:'ancient temple ruins, historical civilization, archaeology, cinematic 2D illustration'},
  'life-lessons':{caption:'Às vezes, a maior mudança começa depois de uma escolha difícil.',cartoon:'reflective person at sunset, emotional life moment, cinematic 2D illustration'},
  motivation:{caption:'Disciplina é continuar quando a motivação já foi embora.',cartoon:'athlete training at sunrise, determination, dynamic cinematic 2D illustration'},
  science:{caption:'O universo é muito mais estranho do que parece à primeira vista.',cartoon:'space telescope, stars and galaxy, science documentary 2D illustration'},
  'true-stories':{caption:'Essa história aconteceu de verdade — e o desfecho surpreendeu muita gente.',cartoon:'real human documentary story, authentic street setting, cinematic 2D illustration'},
  animals:{caption:'Na natureza, cada comportamento existe por uma razão.',cartoon:'wild animal in correct natural habitat, wildlife documentary 2D illustration'}
};
const previewCache={},sceneSyncTimers=new Map();let previewRequestToken=0;
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function msg(t,e=false){const m=$('message');if(!m)return;m.hidden=!t;m.textContent=t;m.style.color=e?'#ffb4b4':''}
function goStep(n){currentStep=Math.max(1,Math.min(4,Number(n)||1));document.querySelectorAll('.stage').forEach(s=>s.classList.toggle('active',Number(s.dataset.stage)===currentStep));document.querySelectorAll('.step-tab').forEach(b=>b.classList.toggle('active',Number(b.dataset.step)===currentStep));window.scrollTo({top:0,behavior:'smooth'})}
function badge(r){if(r.status!=='completed')return['Processando','warn'];if(r.conclusion==='success')return['Concluído','ok'];if(r.conclusion==='cancelled')return['Cancelado','bad'];return['Falhou','bad']}
async function status(){try{const r=await fetch('/api/status',{cache:'no-store'}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha no status');$('quotaText').textContent=`${d.usedToday}/${d.dailyLimit||10} • ${d.remaining} restantes`;if($('generateBtn'))$('generateBtn').disabled=d.remaining<=0||!currentPlan;$('runs').innerHTML=(d.runs||[]).map(x=>{const[b,c]=badge(x),p=Math.max(0,Math.min(100,Number(x.progress??0))),dl=x.downloadUrl?`<a class="download" href="${x.downloadUrl}" target="_blank">Baixar MP4</a>`:'';return `<div class="run"><div><div class="run-title">${esc(x.name)}</div><span class="badge ${c}">${b}</span><div class="progress-wrap"><div class="progress-head"><span>${esc(x.stage||b)}</span><strong>${p}%</strong></div><div class="progress-track"><div class="progress-fill" style="width:${p}%"></div></div></div></div>${dl}</div>`}).join('')||'<p class="muted">Nenhum render ainda.</p>'}catch(e){$('quotaText').textContent='indisponível';$('runs').innerHTML=`<p class="muted">${esc(e.message)}</p>`}}
function previewTheme(){return previewThemes[selectedPresetKey]||previewThemes.default}
function cartoonPreviewUrl(){const theme=previewTheme(),style=$('cartoonStyle').value,styleText={"classic-2d":'polished classic 2D animation',comic:'cinematic comic book art','paper-cut':'layered paper cutout illustration','retro-surreal':'retro surreal 2D illustration',interdimensional:'vibrant sci-fi surreal 2D illustration'}[style]||'polished 2D animation';const prompt=`${theme.cartoon}, ${styleText}, vertical 9:16, no text, no watermark`;return `https://image.pollinations.ai/prompt/${encodeURIComponent(prompt)}?width=512&height=910&nologo=true&seed=20260829&enhance=true`}
async function loadPreviewMedia(){const visual=$('visualStyle').value,photo=$('previewPhoto'),fallback=$('previewIllustration'),token=++previewRequestToken;fallback.hidden=true;photo.hidden=false;if(visual==='cartoon'){photo.src=cartoonPreviewUrl();photo.alt='Prévia ilustrada do tema selecionado';return}const key=selectedPresetKey||'custom';if(previewCache[key]){photo.src=previewCache[key];photo.alt='Foto real de pré-visualização';return}try{const r=await fetch(`/api/preview-media?preset=${encodeURIComponent(key)}`,{cache:'default'}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao carregar prévia');if(token!==previewRequestToken)return;previewCache[key]=d.url;photo.src=d.url;photo.alt=d.alt||'Foto real de pré-visualização'}catch(e){if(token!==previewRequestToken)return;photo.hidden=true;fallback.hidden=false}}
function updatePreview(){const visual=$('visualStyle').value,media=$('mediaMode').value,font=$('captionFont').value,size=Number($('captionSize').value),cap=$('captions').value==='on';$('cartoonStyleWrap').hidden=visual!=='cartoon';$('previewModeBadge').textContent=`${visual==='cartoon'?'DESENHO':'REALISTA'} • ${media==='photos'?'FOTOS':media==='videos'?'VÍDEOS':'MISTO'}`;$('mediaChip').textContent=media==='photos'?'Somente fotos':media==='videos'?(visual==='cartoon'?'Ilustração animada':'Somente vídeos'):'Fotos + vídeos';$('previewFontLabel').textContent=`${font} • ${size}`;const c=$('previewCaption');c.textContent=previewTheme().caption;c.style.fontFamily=`"${font}",sans-serif`;c.style.fontSize=`${Math.max(12,Math.round(size*.48))}px`;c.hidden=!cap;$('videoMotion').classList.toggle('active',media!=='photos');$('visualNotice').textContent=visual==='realistic'?'Modo Realista: o render busca fotos e/ou vídeos do Pexels de acordo com cada cena.':media==='videos'?'Modo Desenho: as cenas são ilustrações temáticas e recebem movimento de câmera.':'Modo Desenho: cada cena usa uma ilustração coerente com o roteiro.';loadPreviewMedia()}
function applyPreset(k){const p=presets[k];if(!p)return;selectedPresetKey=k;$('tone').value=p.tone;$('music').value=p.music;document.querySelectorAll('.preset').forEach(b=>b.classList.toggle('active',b.dataset.preset===k));$('presetStatus').textContent=`${p.label} selecionado. ${k==='biblical'||k==='devotional'?'Deixe o tema vazio para receber uma opção aleatória.':'Você pode escrever um tema específico ou deixar vazio.'}`;$('musicVolumeWrap').hidden=$('music').value==='off';updatePreview()}
function sceneBadgeText(scene){const visual=$('visualStyle').value,media=$('mediaMode').value;return visual==='cartoon'?'desenho':media==='videos'?'vídeo':media==='photos'?'foto':scene.recommended_media==='video'?'vídeo':'foto'}
function setSceneSyncState(el,text,kind=''){const s=el.querySelector('.scene-sync');if(!s)return;s.textContent=text;s.className=`scene-sync ${kind}`.trim()}
async function refreshSceneQuery(el,i){if(!currentPlan?.scenes?.[i])return;const timer=sceneSyncTimers.get(i);if(timer)clearTimeout(timer);sceneSyncTimers.delete(i);const v=el.querySelector('.v').value.trim(),n=el.querySelector('.n').value.trim();if(!v&&!n)return;setSceneSyncState(el,'Atualizando busca da mídia…','syncing');try{const r=await fetch('/api/scene-query',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({visualDescription:v,narration:n,presetKey:selectedPresetKey||currentPlan.niche_key||'custom',visualStyle:$('visualStyle').value,mediaMode:$('mediaMode').value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao atualizar busca');el.querySelector('.q').value=d.visual_query||v;el.querySelector('.qb').value=d.visual_query_backup||d.visual_query||v;el.querySelector('.rm').value=d.recommended_media==='video'?'video':'image';currentPlan.scenes[i].visual_description=v;currentPlan.scenes[i].visual_query=el.querySelector('.q').value;currentPlan.scenes[i].visual_query_backup=el.querySelector('.qb').value;currentPlan.scenes[i].recommended_media=el.querySelector('.rm').value;el.dataset.visualDirty='0';const b=el.querySelector('.badge');if(b)b.textContent=sceneBadgeText(currentPlan.scenes[i]);setSceneSyncState(el,'Busca da mídia atualizada','ok')}catch(e){el.dataset.visualDirty='1';setSceneSyncState(el,'Não consegui atualizar agora; vou tentar novamente antes de gerar.','bad')}}
function scheduleSceneQueryRefresh(el,i){el.dataset.visualDirty='1';setSceneSyncState(el,'Alteração detectada • atualizando em instantes…','pending');const old=sceneSyncTimers.get(i);if(old)clearTimeout(old);sceneSyncTimers.set(i,setTimeout(()=>refreshSceneQuery(el,i),650))}
function markAllVisualDirty(){if(!currentPlan)return;document.querySelectorAll('.scene').forEach((el,i)=>scheduleSceneQueryRefresh(el,i))}
async function syncDirtyScenes(){const dirty=[...document.querySelectorAll('.scene')].filter(el=>el.dataset.visualDirty==='1');for(const el of dirty)await refreshSceneQuery(el,Number(el.dataset.i))}
function bindSceneEditors(){document.querySelectorAll('.scene').forEach((el,i)=>{const v=el.querySelector('.v'),n=el.querySelector('.n');v.addEventListener('input',()=>scheduleSceneQueryRefresh(el,i));n.addEventListener('input',()=>{if(currentPlan?.scenes?.[i])currentPlan.scenes[i].narration=n.value.trim()})})}
function renderPlan(p){currentPlan=p;if(!$('topic').value.trim())$('topic').value=p.title||'';$('planTitle').textContent=p.title||'Revise seu storyboard';$('planSummary').textContent=p.summary||'';$('sceneEditor').innerHTML=p.scenes.map((s,i)=>`<article class="scene" data-i="${i}" data-visual-dirty="0"><div class="scene-head"><span class="scene-number">${i+1}</span><div class="scene-title">${esc(s.beat||`Cena ${i+1}`)}</div><span class="badge">${sceneBadgeText(s)}</span></div><div class="scene-grid"><div><label>Narração</label><textarea class="n">${esc(s.narration||'')}</textarea></div><div><label>Visual da cena</label><textarea class="v">${esc(s.visual_description||'')}</textarea><div class="scene-sync">A busca da mídia acompanha esta descrição.</div></div></div><input class="q" type="hidden" value="${esc(s.visual_query||'cinematic scene')}"><input class="qb" type="hidden" value="${esc(s.visual_query_backup||s.visual_query||'cinematic scene')}"><input class="rm" type="hidden" value="${esc(s.recommended_media||'image')}"></article>`).join('');bindSceneEditors();$('reviewNextBtn').disabled=false;$('generateBtn').disabled=false;goStep(3);status()}
function collect(){const p=JSON.parse(JSON.stringify(currentPlan));document.querySelectorAll('.scene').forEach((el,i)=>{p.scenes[i].narration=el.querySelector('.n').value.trim();p.scenes[i].visual_description=el.querySelector('.v').value.trim();p.scenes[i].visual_query=el.querySelector('.q').value.trim()||p.scenes[i].visual_description||'cinematic scene';p.scenes[i].visual_query_backup=el.querySelector('.qb').value.trim()||p.scenes[i].visual_query;p.scenes[i].recommended_media=el.querySelector('.rm').value==='video'?'video':'image'});return p}
async function plan(){const topic=$('topic').value.trim();if(!topic&&!selectedPresetKey){goStep(1);return msg('Escreva o tema ou escolha uma categoria.',true)}$('planBtn').disabled=true;msg('Criando roteiro e storyboard…');try{const r=await fetch('/api/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic,presetKey:selectedPresetKey,duration:Number($('duration').value),tone:$('tone').value,visualStyle:$('visualStyle').value,cartoonStyle:$('cartoonStyle').value,mediaMode:$('mediaMode').value,references:[]})}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao criar roteiro');renderPlan(d.plan);msg('Storyboard pronto. Revise antes de gerar.')}catch(e){msg(e.message,true)}finally{$('planBtn').disabled=false}}
document.querySelectorAll('.step-tab').forEach(b=>b.addEventListener('click',()=>{const n=Number(b.dataset.step);if(n>=3&&!currentPlan)return;goStep(n)}));document.querySelectorAll('.next-btn').forEach(b=>b.addEventListener('click',()=>{if(Number(b.dataset.next)===2&&!$('topic').value.trim()&&!selectedPresetKey)return msg('Escreva o tema ou escolha uma categoria.',true);goStep(b.dataset.next)}));document.querySelectorAll('.prev-btn').forEach(b=>b.addEventListener('click',()=>goStep(b.dataset.prev)));document.querySelectorAll('.preset').forEach(b=>b.addEventListener('click',()=>applyPreset(b.dataset.preset)));$('planBtn').addEventListener('click',plan);$('reviewNextBtn').addEventListener('click',async()=>{if(!currentPlan)return;$('reviewNextBtn').disabled=true;await syncDirtyScenes();$('reviewNextBtn').disabled=false;goStep(4)});$('refreshBtn').addEventListener('click',status);$('refreshRunsBtn').addEventListener('click',status);$('music').addEventListener('change',()=>$('musicVolumeWrap').hidden=$('music').value==='off');['cartoonStyle','captionFont','captionSize','captions'].forEach(id=>$(id).addEventListener('change',updatePreview));['visualStyle','mediaMode'].forEach(id=>$(id).addEventListener('change',()=>{updatePreview();markAllVisualDirty()}));$('previewPhoto').addEventListener('error',()=>{$('previewPhoto').hidden=true;$('previewIllustration').hidden=false});
$('generateBtn').addEventListener('click',async()=>{if(!currentPlan)return;$('generateBtn').disabled=true;msg('Conferindo suas alterações da revisão…');try{await syncDirtyScenes();const p=collect();if(p.scenes.some(s=>!s.narration)){goStep(3);throw Error('Existe cena sem narração.')}msg('Enviando vídeo para renderização…');const r=await fetch('/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:$('topic').value.trim()||p.title,presetKey:selectedPresetKey,plan:p,duration:Number($('duration').value),tone:$('tone').value,visualStyle:$('visualStyle').value,cartoonStyle:$('cartoonStyle').value,mediaMode:$('mediaMode').value,voice:$('voice').value,captions:$('captions').value,captionFont:$('captionFont').value,captionSize:Number($('captionSize').value),music:$('music').value,musicVolume:$('musicVolume').value})}),d=await r.json();if(!r.ok)throw Error(d.error||'Falha ao iniciar');msg('Render iniciado. Acompanhe o progresso nesta etapa.');await status();setTimeout(status,3500)}catch(e){msg(e.message,true);$('generateBtn').disabled=false}});
$('musicVolumeWrap').hidden=$('music').value==='off';updatePreview();goStep(1);setInterval(status,12000);setTimeout(status,1200);