const { gh, config, usedToday, workflowRuns } = require('../lib/github');
const { requireAuth } = require('../lib/auth');
const {narrationWordCount,minNarrationWords}=require('../lib/content-freshness');
const DAILY_LIMIT=10;
const BLOCKED_RX=/\b(catholic|católico|católica|catolicismo|cathedral|catedral|pope|papa|papal|rosary|terço|crucifix|crucifixo|statue|estátua|saint|santo|santa|virgin mary|virgem maria|madonna|marian|mariana|mass|missa|monstrance|ostensório|basilica|basílica|islam|islã|islão|islamic|islâmico|islâmica|muslim|muçulmano|muçulmana|mosque|mesquita|quran|corão|koran|mecca|meca|medina|ramadan|minaret|minarete|imam|candomblé|candomble|umbanda|orixá|orixa|orisha|terreiro|pombagira|pomba gira|iemanjá|iemanja|ogum|oxum|oxóssi|oxossi|xangô|xango|iansã|iansa|obaluaiê|obaluae)\b/i;
function validReferenceB64(value){const s=String(value||'').trim();return s.length>=1200&&s.length<=32000&&/^[A-Za-z0-9+/]+=*$/.test(s)}
function compact(v,max=18){return String(v||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean).slice(0,max).join(' ')}
function extractJson(text){const raw=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const m=raw.match(/\{[\s\S]*\}/);if(!m)throw Error('json inválido');return JSON.parse(m[0])}
function cleanHashtags(value){const arr=Array.isArray(value)?value:String(value||'').split(/[\s,]+/);return [...new Set(arr.map(x=>String(x).trim().replace(/^#+/,'').replace(/[^\p{L}\p{N}_]/gu,'')).filter(Boolean))].slice(0,8).map(x=>`#${x}`)}
function socialFallback(plan){const title=String(plan.title||'').trim().slice(0,90);const hashtags=cleanHashtags(plan.hashtags||[]);const tags=hashtags.length?hashtags.join(' '):'#Reels #TikTok #ParaVoce';const base=String(plan.summary||plan.description||plan.scenes?.[0]?.narration||'').trim().slice(0,420);return{title,tiktok:`${base}\n\n${tags}`.trim(),instagram:`${base}\n\n${tags}`.trim(),hashtags}}
async function finalCreativeReview(plan,{topic,presetKey,tone,visualStyle,mediaMode,duration,voice}){
  const key=process.env.GROQ_API_KEY;if(!key)return{plan,social:socialFallback(plan)};
  const scenes=plan.scenes.map((s,i)=>({i:i+1,narration:s.narration,visual_description:s.visual_description,recommended_media:s.recommended_media}));
  const prompt=`Você é editor-chefe de vídeos verticais para TikTok e Instagram. Faça uma REVISÃO FINAL sem mudar os fatos, a mensagem central ou a duração planejada.\nTEMA: ${topic}\nCATEGORIA: ${presetKey}\nTOM: ${tone}\nVISUAL: ${visualStyle}\nMÍDIA: ${mediaMode}\nDURAÇÃO: ${duration}s\nNARRAÇÃO: ${voice==='off'?'desativada; o texto do roteiro ainda guia cenas e legendas':'ativada'}\nTÍTULO ATUAL: ${plan.title}\nRESUMO: ${plan.summary||''}\nCENAS: ${JSON.stringify(scenes)}\n\nOBJETIVOS OBRIGATÓRIOS:\n1. Retenção: a PRIMEIRA CENA precisa abrir com o melhor gancho possível para o assunto. Pode ser pergunta, afirmação surpreendente, promessa, conflito ou curiosidade. NÃO force pergunta; escolha o formato mais forte e natural. O gancho deve entrar direto no conteúdo, sem clickbait enganoso.\n2. Preserve aproximadamente o mesmo número total de palavras da narração atual. Não encurte o roteiro.\n3. COERÊNCIA VISUAL ABSOLUTA: para CADA cena, visual_description deve representar literalmente a fala daquela cena, com sujeito, ação, lugar, época e detalhe importante corretos. Não use imagens genéricas só porque combinam com o clima.\n4. Para cada cena gere visual_query e visual_query_backup EM INGLÊS, específicas, concretas e semanticamente ligadas à narração daquela cena. Elas precisam buscar/gerar exatamente o que está sendo dito.\n5. recommended_media: image para cena histórica, nomeada, específica, sobrenatural ou difícil de encontrar com precisão; video para ação real genérica cuja filmagem pronta possa representar exatamente a fala.\n6. Não repita enquadramento/objeto sem motivo narrativo.\n7. Crie pacote de publicação em português do Brasil para TikTok e Instagram: um título curto e forte; descrição TikTok direta, com palavras-chave naturais, CTA leve quando adequado e hashtags relevantes; descrição Instagram um pouco mais completa, legível e natural, também com CTA leve quando adequado.\n8. Use somente 4 a 8 hashtags altamente relacionadas ao assunto/nicho. Não encha de hashtags genéricas e não prometa viralização. Misture termos específicos do tema com termos do nicho quando fizer sentido.\n9. A copy deve despertar curiosidade sem revelar todo o desfecho e sem contradizer o vídeo.\n10. Se o conteúdo for factual, não invente fatos para torná-lo mais chamativo.\n\nRetorne SOMENTE JSON válido neste formato:\n{"title":"...","summary":"...","description":"...","hashtags":["..."],"scenes":[{"i":1,"narration":"...","visual_description":"...","visual_query":"...","visual_query_backup":"...","recommended_media":"image"}],"social":{"title":"...","tiktok":"...","instagram":"...","hashtags":["..."]}}`;
  try{
    const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'qwen/qwen3.8-27b',temperature:.46,max_completion_tokens:4200,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});
    const data=await response.json();if(!response.ok)throw Error('review');const out=extractJson(data.choices?.[0]?.message?.content||'');
    if(!Array.isArray(out.scenes)||out.scenes.length!==plan.scenes.length)throw Error('scenes');
    const originalWords=narrationWordCount(plan),newWords=out.scenes.reduce((n,s)=>n+String(s.narration||'').split(/\s+/).filter(Boolean).length,0);
    const useNarration=voice==='off'||(newWords>=Math.round(originalWords*.88)&&newWords<=Math.round(originalWords*1.16));
    const reviewed={...plan,title:String(out.title||plan.title).slice(0,180),summary:String(out.summary||plan.summary||'').slice(0,700),description:String(out.description||plan.description||'').slice(0,1000),hashtags:cleanHashtags(out.hashtags||plan.hashtags),scenes:plan.scenes.map((old,i)=>{const s=out.scenes[i]||{};return{...old,narration:useNarration?String(s.narration||old.narration).trim():old.narration,visual_description:String(s.visual_description||old.visual_description).trim().slice(0,900),visual_query:compact(s.visual_query||old.visual_query,18).slice(0,210),visual_query_backup:compact(s.visual_query_backup||old.visual_query_backup||s.visual_query,18).slice(0,210),recommended_media:s.recommended_media==='video'?'video':'image'}})};
    if(BLOCKED_RX.test(JSON.stringify(reviewed)))throw Error('blocked');
    const socialRaw=out.social||{},social={title:String(socialRaw.title||reviewed.title).trim().slice(0,100),tiktok:String(socialRaw.tiktok||'').trim().slice(0,1200),instagram:String(socialRaw.instagram||'').trim().slice(0,1800),hashtags:cleanHashtags(socialRaw.hashtags||reviewed.hashtags)};
    if(!social.tiktok||!social.instagram){const fb=socialFallback(reviewed);if(!social.tiktok)social.tiktok=fb.tiktok;if(!social.instagram)social.instagram=fb.instagram}
    return{plan:reviewed,social};
  }catch(error){console.error('finalCreativeReview',error);return{plan,social:socialFallback(plan)}}
}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 try{
  const activeData=await workflowRuns();const active=(activeData.workflow_runs||[]).find(r=>r.name==='Generate Short'&&r.status!=='completed');if(active)return res.status(409).json({error:'Já existe uma geração em andamento. Aguarde concluir ou cancele antes de iniciar outra.',active:true});
  const{repo}=config(),topic=String(req.body?.topic||'').trim(),plan=req.body?.plan;if(!topic)return res.status(400).json({error:'Informe o tema.'});if(BLOCKED_RX.test(topic))return res.status(400).json({error:'Esse tipo de conteúdo religioso não faz parte da proposta deste Studio.'});if(!plan||!Array.isArray(plan.scenes)||plan.scenes.length<6)return res.status(400).json({error:'Crie e aprove um plano válido antes de gerar.'});if(BLOCKED_RX.test(JSON.stringify(plan)))return res.status(400).json({error:'O roteiro contém um contexto religioso fora da proposta do Studio. Revise as cenas antes de gerar.'});
  const duration=Math.min(70,Math.max(60,Number(req.body?.duration||65))),tone=String(req.body?.tone||'cinematic').slice(0,40),allowedPresets=['biblical','devotional','cinematic','mysteries','ancient','motivation','science','true-stories','horror','horror-real','life-lessons','animals'],presetKey=allowedPresets.includes(req.body?.presetKey)?req.body.presetKey:'custom';
  const visualStyle=['realistic','cartoon'].includes(req.body?.visualStyle)?req.body.visualStyle:'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid',cartoonStyle=['interdimensional','paper-cut','retro-surreal','classic-2d','comic'].includes(req.body?.cartoonStyle)?req.body.cartoonStyle:'classic-2d';
  const mediaSource=req.body?.mediaSource==='reference'?'reference':'auto',referenceImageB64=String(req.body?.referenceImageB64||'').trim();if(mediaSource==='reference'&&!validReferenceB64(referenceImageB64))return res.status(400).json({error:'Envie uma foto de referência válida antes de gerar.'});
  const voices=['off','gemini:Sulafat','gemini:Gacrux','gemini:AlgenibDeep','gemini:GacruxDeep','gemini:Achernar','gemini:Charon','gemini:Kore','gemini:Puck','pt-BR-AntonioNeural','pt-BR-FranciscaNeural','pt-BR-ThalitaNeural'],voice=voices.includes(req.body?.voice)?req.body.voice:'gemini:Sulafat',voicePitch=['low','default','high'].includes(req.body?.voicePitch)?req.body.voicePitch:'default',voiceSpeed=['default','fast','veryfast'].includes(req.body?.voiceSpeed)?req.body.voiceSpeed:'default',captions=req.body?.captions==='off'?'off':'on';
  const fonts=['Montserrat','Roboto','Lato','Noto Sans','Noto Serif'],captionFont=fonts.includes(req.body?.captionFont)?req.body.captionFont:'Montserrat',captionSize=[42,56,70,84].includes(Number(req.body?.captionSize))?Number(req.body.captionSize):56;
  const allowedMusic=new Set(['off','viral-pulse','cinematic-rise','mystery-tension','emotional-ambient','epic-ancient']),music=allowedMusic.has(req.body?.music)?req.body.music:'off',musicVolume=['low','medium','high'].includes(req.body?.musicVolume)?req.body.musicVolume:'medium';
  let cleanPlan={title:String(plan.title||topic).slice(0,180),summary:String(plan.summary||'').slice(0,700),description:String(plan.description||'').slice(0,1000),hashtags:cleanHashtags(plan.hashtags||[]),niche_key:String(plan.niche_key||presetKey).slice(0,40),visual_context:String(plan.visual_context||'').slice(0,900),scenes:plan.scenes.slice(0,10).map((s,i)=>({beat:String(s.beat||`Cena ${i+1}`).slice(0,100),narration:String(s.narration||'').trim().slice(0,900),visual_description:String(s.visual_description||'').trim().slice(0,900),visual_query:String(s.visual_query||'cinematic scene').trim().slice(0,210),visual_query_backup:String(s.visual_query_backup||s.visual_query||'cinematic scene').trim().slice(0,210),recommended_media:s.recommended_media==='video'?'video':'image'}))};
  if(voice!=='off'&&cleanPlan.scenes.some(s=>!s.narration))return res.status(400).json({error:'Uma ou mais cenas estão sem narração.'});
  if(voice!=='off'){const words=narrationWordCount(cleanPlan),minimum=minNarrationWords(duration,voiceSpeed);if(words<minimum)return res.status(400).json({error:`O roteiro ficou curto para ${duration} segundos nessa velocidade. Recrie o roteiro antes de gerar.`,shortScript:true,words,minimum});}
  const reviewed=await finalCreativeReview(cleanPlan,{topic,presetKey,tone,visualStyle,mediaMode,duration,voice});cleanPlan=reviewed.plan;
  if(voice!=='off'){const words=narrationWordCount(cleanPlan),minimum=minNarrationWords(duration,voiceSpeed);if(words<minimum)return res.status(400).json({error:'A revisão final deixou o roteiro curto demais. Recrie o roteiro antes de gerar.',shortScript:true,words,minimum});}
  const planJson=JSON.stringify(cleanPlan);if(planJson.length>56000)return res.status(400).json({error:'O plano ficou grande demais.'});
  const used=await usedToday();if(used>=DAILY_LIMIT)return res.status(429).json({error:`O limite configurado de ${DAILY_LIMIT} criações de hoje já foi usado.`,usedToday:used,remaining:0});const requestId=`studio-${Date.now()}`;
  await gh(`/repos/${repo}/actions/workflows/generate-short.yml/dispatches`,{method:'POST',body:JSON.stringify({ref:'main',inputs:{topic,plan_json:planJson,duration:String(duration),tone,niche_key:presetKey,visual_style:visualStyle,cartoon_style:cartoonStyle,media_mode:mediaMode,media_source:mediaSource,reference_image_b64:mediaSource==='reference'?referenceImageB64:'',voice,voice_pitch:voicePitch,voice_speed:voiceSpeed,captions,caption_font:captionFont,caption_size:String(captionSize),music,music_volume:musicVolume,request_id:requestId}})});
  const engines={script:'Inteligência principal',visual:mediaSource==='reference'?'Criação visual por referência':'Criação visual inteligente com alternativas automáticas',voice:voice==='off'?'Sem narração':'Narração natural com alternativas automáticas'};
  return res.status(202).json({ok:true,requestId,usedToday:used,dailyLimit:DAILY_LIMIT,remaining:DAILY_LIMIT-used,engines,mediaSource,social:reviewed.social,finalTitle:cleanPlan.title});
 }catch(error){console.error(error);return res.status(500).json({error:'Falha ao iniciar geração.'})}
};