const { requireAuth } = require('../lib/auth');
const {buildAvoidance,avoidText,targetNarrationWords,minNarrationWords,maxNarrationWords,narrationWordCount,tooSimilar}=require('../lib/content-freshness');
function extractJson(text){const raw=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const m=raw.match(/\{[\s\S]*\}/);if(!m)throw Error('Não foi possível criar um roteiro válido.');return JSON.parse(m[0])}
function compact(v,max=16){return String(v||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean).slice(0,max).join(' ')}
async function ask(key,prompt){const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'qwen/qwen3.8-27b',temperature:.64,max_completion_tokens:3800,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});const data=await response.json();if(response.status===429){const e=Error('rate');e.rate=true;throw e}if(!response.ok)throw Error('Falha temporária');return extractJson(data.choices?.[0]?.message?.content||'')}
module.exports=async function handler(req,res){
  if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
  try{
    const key=process.env.GROQ_API_KEY;if(!key)return res.status(500).json({error:'Serviço de criação indisponível.'});
    const topic=String(req.body?.topic||'').trim(),duration=Math.min(70,Math.max(60,Number(req.body?.duration||65))),tone=String(req.body?.tone||'dramatic'),visualStyle=req.body?.visualStyle==='cartoon'?'cartoon':'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid',voiceSpeed=['default','fast','veryfast'].includes(req.body?.voiceSpeed)?req.body.voiceSpeed:'default';
    const sceneCount=duration<=60?8:duration>=70?10:9,targetWords=targetNarrationWords(duration,voiceSpeed),minWords=minNarrationWords(duration,voiceSpeed),maxWords=maxNarrationWords(duration,voiceSpeed),avoid=await buildAvoidance(req.body);
    const subject=topic||'Crie uma história ORIGINAL de terror e suspense psicológico. Escolha situação, local, protagonista e ameaça diferentes das criações recentes.';
    const base=`Crie roteiro e storyboard para UM Short vertical de terror e suspense em português do Brasil.\nASSUNTO: ${subject}\nDURAÇÃO: ${duration}s | TOM: ${tone} | VISUAL: ${visualStyle} | MÍDIA: ${mediaMode}\n\nVARIEDADE OBRIGATÓRIA:\n- Cada criação precisa ser uma história diferente dentro de terror e suspense.\n- Não repita título, cenário central, protagonista, ameaça, objeto-chave, reviravolta nem encerramento das criações recentes.\n- Se o usuário deu um assunto, mantenha o assunto, mas mude recorte, acontecimentos e estrutura.\nCONTEÚDOS RECENTES A EVITAR:\n${avoidText(avoid)}\n\nNARRAÇÃO:\n- O texto completo deve ter entre ${minWords} e ${maxWords} palavras, alvo ${targetWords}; nunca menos de ${minWords}.\n- Distribua em ${sceneCount} cenas com conteúdo suficiente em cada uma.\n- Gancho inquietante, tensão progressiva, pistas, falsa segurança, clímax e fechamento forte.\n- Português brasileiro natural, fluido e apropriado para narração.\n- O medo deve vir principalmente de atmosfera, antecipação, isolamento, comportamento estranho, som sugerido, espaço e descoberta.\n- Pode haver ficção sobrenatural ou terror psicológico, sem depender de violência gráfica.\n\nDIREÇÃO VISUAL:\n- visual_context em INGLÊS com continuidade de local, horário, paleta, iluminação, textura, personagens e câmera.\n- Cada visual_description deve mostrar uma ação concreta específica.\n- Use composição de suspense: negative space, deep shadows, practical light, reflections, silhouettes, partially obscured spaces, long corridors, doorways e subtle background detail quando fizer sentido.\n- Evite gore e choque gráfico como preenchimento.\n- visual_query e visual_query_backup em INGLÊS, positivas, específicas, 8 a 16 palavras.\n- Preserve continuidade.\n- Em hybrid prefira image para cenas únicas/sobrenaturais e video para movimento genérico útil; em photos use image; em videos use video.\nRetorne SOMENTE JSON válido com: title, summary, description, hashtags, niche_key, visual_context e scenes. Cada scene: beat, narration, visual_description, visual_query, visual_query_backup, recommended_media.`;
    let plan=null;
    for(let attempt=0;attempt<2;attempt++){
      try{plan=await ask(key,base+(attempt?`\nREFAÇA DO ZERO: a tentativa anterior ficou curta ou parecida. Garanta pelo menos ${minWords} palavras e outro título/ângulo.`:''))}catch(e){if(e.rate)return res.status(429).json({error:'Muita atividade no momento. Tente novamente em alguns instantes.',retryAfterSeconds:5});throw e}
      if(Array.isArray(plan.scenes)&&plan.scenes.length>=6&&narrationWordCount(plan)>=minWords&&(topic||!tooSimilar(plan.title,avoid)))break;plan=null;
    }
    if(!plan)throw Error('Roteiro curto ou repetitivo');
    plan.niche_key='horror';plan.visual_context=String(plan.visual_context||'psychological horror, cinematic low key lighting, deep shadows, restrained color palette, consistent characters and location').slice(0,900);const seen=new Set();
    plan.scenes=plan.scenes.slice(0,10).map((s,i)=>{const narration=String(s.narration||'').trim(),desc=String(s.visual_description||'').trim().slice(0,900);let primary=compact(s.visual_query||desc||narration,16),backup=compact(s.visual_query_backup||primary,16),anchor='psychological horror suspense cinematic low key lighting non graphic';primary=`${primary} ${anchor}`.replace(/\s+/g,' ').slice(0,210);backup=`${backup} alternate angle ${anchor}`.replace(/\s+/g,' ').slice(0,210);if(seen.has(primary.toLowerCase()))primary=`${compact(desc,12)} suspense scene ${i+1} ${anchor}`.slice(0,210);seen.add(primary.toLowerCase());let recommended=s.recommended_media==='video'?'video':'image';if(mediaMode==='photos')recommended='image';if(mediaMode==='videos')recommended='video';return{beat:String(s.beat||`Cena ${i+1}`).slice(0,100),narration,visual_description:desc,visual_query:primary,visual_query_backup:backup,recommended_media:recommended}});
    return res.status(200).json({plan,preset:'Terror e Suspense'});
  }catch(error){console.error('horror-plan',error);return res.status(500).json({error:'Não foi possível criar a história agora. Tente novamente em alguns instantes.'})}
};