const { requireAuth } = require('../lib/auth');
const {buildAvoidance,avoidText,targetNarrationWords,minNarrationWords,maxNarrationWords,narrationWordCount,tooSimilar,pickUnused}=require('../lib/content-freshness');
const REAL_CASES=[
{name:'O desaparecimento dos faroleiros das Ilhas Flannan em 1900',note:'três faroleiros desapareceram; use somente fatos documentados e trate teorias como teorias'},
{name:'O Mary Celeste encontrado abandonado em 1872',note:'navio encontrado sem a tripulação; não invente causa sobrenatural'},
{name:'O incidente do Passo Dyatlov em 1959',note:'grupo morreu nos Urais; diferencie evidências e hipóteses'},
{name:'O caso dos Cinco de Yuba County em 1978',note:'desaparecimento e mortes com aspectos ainda discutidos; não invente diálogos'},
{name:'O desaparecimento das crianças Sodder em 1945',note:'caso controverso após incêndio; separe alegações de fatos comprovados'},
{name:'Os assassinatos não solucionados de Hinterkaifeck em 1922',note:'conte de forma não gráfica, focando nos fatos estranhos documentados'},
{name:'A Praga da Dança de Estrasburgo em 1518',note:'evento histórico documentado; as causas são debatidas'},
{name:'O desastre do Lago Nyos em 1986',note:'tragédia real causada por liberação de dióxido de carbono; não invente mistério'},
{name:'O desaparecimento do voo Flying Tiger Line 739 em 1962',note:'aeronave desapareceu no Pacífico; mantenha os fatos e buscas documentadas'},
{name:'O naufrágio e a sobrevivência do Essex em 1820',note:'evento real; narre de modo factual e não gráfico'}
];
function extractJson(text){const raw=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const m=raw.match(/\{[\s\S]*\}/);if(!m)throw Error('Não foi possível criar um roteiro válido.');return JSON.parse(m[0])}
function compact(v,max=16){return String(v||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean).slice(0,max).join(' ')}
async function ask(key,prompt,temp){const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'qwen/qwen3.8-27b',temperature:temp,max_completion_tokens:4000,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});const data=await response.json();if(response.status===429){const e=Error('rate');e.rate=true;throw e}if(!response.ok)throw Error('Falha temporária');return extractJson(data.choices?.[0]?.message?.content||'')}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 try{
  const key=process.env.GROQ_API_KEY;if(!key)return res.status(500).json({error:'Serviço de criação indisponível.'});
  const requested=String(req.body?.presetKey||''),mode=requested==='analog-horror'?'analog-horror':requested==='horror-real'?'horror-real':'horror',real=mode==='horror-real',analog=mode==='analog-horror',topic=String(req.body?.topic||'').trim(),duration=Math.min(70,Math.max(60,Number(req.body?.duration||65))),tone=String(req.body?.tone||'dramatic'),visualStyle=req.body?.visualStyle==='cartoon'?'cartoon':'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid',voiceSpeed=['default','fast','veryfast'].includes(req.body?.voiceSpeed)?req.body.voiceSpeed:'default';
  const sceneCount=duration<=60?8:duration>=70?10:9,targetWords=targetNarrationWords(duration,voiceSpeed),minWords=minNarrationWords(duration,voiceSpeed),maxWords=maxNarrationWords(duration,voiceSpeed),avoid=await buildAvoidance(req.body);
  const picked=real?pickUnused(REAL_CASES,avoid,x=>x.name):null,subject=topic||(real?picked.name:analog?'Crie uma fita ORIGINAL de terror analógico. Escolha entre transmissão de emergência, treinamento institucional, arquivo confidencial, programa infantil perdido, câmera de segurança ou gravação doméstica. Varie época, local, ameaça e tipo de documento.':'Crie uma história ORIGINAL de terror e suspense psicológico. Escolha situação, local, protagonista e ameaça diferentes das criações recentes.');
  const factual=real?`\nREGRA CENTRAL — HISTÓRIA REAL:\n- Baseie o vídeo somente em acontecimentos reais/documentados.\n- Não invente pessoas, falas, datas, evidências, cartas, gravações ou acontecimentos.\n- Separe fatos confirmados de versões, lendas e hipóteses.\n- Não transforme hipótese sobrenatural em fato.\n- NOTA DO CASO: ${topic?'O usuário definiu o assunto; preserve apenas fatos sustentáveis.':picked.note}\n`:'';
  const analogRules=analog?`\nREGRA CENTRAL — TERROR ANALÓGICO:\n- A história é FICÇÃO e isso deve constar em description e hashtags; nunca alegue que o evento inventado aconteceu de verdade.\n- Apresente tudo como fita, transmissão, arquivo, gravação, treinamento ou alerta de outra época.\n- Comece com identificação curta de arquivo/data/local; estabeleça uma rotina institucional aparentemente normal; introduza uma anomalia pequena; aumente as contradições; revele o perigo; termine com interrupção, instrução impossível ou mensagem incompleta.\n- Evite monstros genéricos, sustos aleatórios, gore e excesso de explicação. O medo deve vir da linguagem burocrática, informação incompleta e deterioração gradual da gravação.\n- Inclua marcas como [RUÍDO], [SINAL INTERROMPIDO] ou [FIM DO ARQUIVO] somente quando ajudarem a narrativa.\n`:'';
  const analogContract=analog?`BÍBLIA OBRIGATÓRIA DA FITA:\n- Retorne analog_bible com exatamente estes campos não vazios: format, year, organization, location, recurring_subject, threat, visual_rules, ending.\n- Esses elementos são imutáveis: todas as cenas pertencem à MESMA fita, local, época e instituição, com o MESMO sujeito recorrente e ameaça.\n- Cada cena continua a ação anterior. Não introduza pessoas, prédios, objetos, símbolos ou monstros sem função narrativa estabelecida.\n- Cada visual_description cita os elementos recorrentes visíveis e descreve uma única ação concreta.\n- O final cumpre exatamente ending, sem trocar a ameaça ou iniciar outra história.\n\n`:'';
  const typeRules=real?'Abra com um fato inquietante real, desenvolva por descoberta ou cronologia e termine distinguindo o que é conhecido do que permanece incerto. Evite sensacionalismo falso.':analog?'Use voz institucional, séria e econômica. O início parece seguro e oficial; cada cena revela uma falha maior. Termine abruptamente, sem explicar completamente a ameaça.':'Use gancho inquietante, tensão progressiva, pistas, falsa segurança, clímax e fechamento forte. O medo deve vir de atmosfera, antecipação, isolamento, comportamento estranho, som sugerido, espaço e descoberta.';
  const visualAnchor=real?'true story documentary suspense historical reconstruction non graphic':analog?'analog horror VHS tape CRT broadcast 1990s scanlines tracking error red black monochrome 4:3 non graphic':'psychological horror suspense cinematic low key lighting non graphic';
  const prompt=`Crie roteiro e storyboard para UM Short vertical de ${real?'TERROR REAL':analog?'TERROR ANALÓGICO FICTÍCIO':'terror e suspense'} em português do Brasil.\nASSUNTO: ${subject}\nDURAÇÃO: ${duration}s | TOM: ${tone} | VISUAL: ${visualStyle} | MÍDIA: ${mediaMode}\n${factual}${analogRules}\nVARIEDADE OBRIGATÓRIA:\n- Cada nova criação precisa ser realmente diferente, mas fiel ao conceito ${real?'de casos reais perturbadores':analog?'de fitas fictícias de terror analógico':'de terror e suspense'}.\n- Não repita título, assunto/caso, cenário central, protagonista, gancho, estrutura ou conclusão dos conteúdos recentes.\n- Se o usuário deu um assunto, preserve o assunto e crie outro recorte e construção narrativa.\nCONTEÚDOS RECENTES A EVITAR:\n${avoidText(avoid)}\n\nNARRAÇÃO:\n- O texto completo DEVE ter entre ${minWords} e ${maxWords} palavras, alvo ${targetWords}; nunca menos de ${minWords}.\n- Distribua em ${sceneCount} cenas com informação suficiente em cada uma.\n- ${typeRules}\n- Português brasileiro natural, fluido e apropriado para narração.\n- Não dependa de violência gráfica.\n\nDIREÇÃO VISUAL:\n- visual_context EM INGLÊS com continuidade de local, época, horário, paleta, iluminação, personagens e câmera.\n- ${real?'Reconstituições devem ser historicamente plausíveis e nunca apresentar invenção como evidência real.':analog?'Cada cena deve parecer quadro de fita VHS 4:3 dentro do vídeo vertical: CRT, broadcast graphics, surveillance framing, institutional diagrams, timestamp, tracking damage, scanlines, red/black/gray palette. Não dependa de texto pequeno gerado dentro da imagem.':'Use composição de suspense como negative space, deep shadows, practical light, reflections, silhouettes, doorways e subtle background detail quando fizer sentido.'}\n- Cada visual_description deve mostrar uma ação concreta e específica.\n- visual_query e visual_query_backup EM INGLÊS, positivas, específicas e entre 8 e 16 palavras.\n- Preserve continuidade e não repita enquadramentos sem motivo.\n- Em hybrid prefira image para cenas específicas/reconstituições e video para movimento genérico útil; em photos use image; em videos use video.\nRetorne SOMENTE JSON válido com: title, summary, description, hashtags, niche_key, visual_context e scenes. Cada scene: beat, narration, visual_description, visual_query, visual_query_backup, recommended_media.`;
  let plan=null;
  for(let attempt=0;attempt<(analog?1:2);attempt++){
   try{plan=await ask(key,analogContract+prompt+(attempt?`\nREFAÇA DO ZERO: a tentativa anterior ficou curta ou parecida. Garanta pelo menos ${minWords} palavras e outro título/ângulo${real?', sem alterar os fatos':''}.`:''),real?.4:analog?.35:.64)}catch(e){if(e.rate)return res.status(429).json({error:'Muita atividade no momento. Tente novamente em alguns instantes.',retryAfterSeconds:5});throw e}
   if(analog&&plan){const scenes=Array.isArray(plan.scenes)?plan.scenes:[],first=scenes[0]||{},last=scenes[scenes.length-1]||{},given=plan.analog_bible&&typeof plan.analog_bible==='object'?plan.analog_bible:{};plan.analog_bible={format:String(given.format||'institutional VHS archive'),year:String(given.year||String(first.narration||plan.title||'').match(/\b(?:19|20)\d{2}\b/)?.[0]||'1994'),organization:String(given.organization||'the institution identified in the opening frame'),location:String(given.location||'the single location established in the opening scene'),recurring_subject:String(given.recurring_subject||'the same central subject introduced in scene one'),threat:String(given.threat||'the same anomaly progressively revealed by the tape'),visual_rules:String(given.visual_rules||plan.visual_context||'red black and gray institutional CRT imagery with unchanged props and character design'),ending:String(given.ending||last.visual_description||last.narration||'the tape ends during the final warning')}}
   const bible=plan?.analog_bible,bibleOk=!analog||(bible&&['format','year','organization','location','recurring_subject','threat','visual_rules','ending'].every(k=>String(bible[k]||'').trim()));
   if(Array.isArray(plan.scenes)&&plan.scenes.length>=6&&narrationWordCount(plan)>=minWords&&bibleOk&&(topic||!tooSimilar(plan.title,avoid)))break;plan=null;
  }
  if(!plan)throw Error('Roteiro curto ou repetitivo');
  plan.niche_key=mode;plan.description=String(plan.description||'').trim();if(analog&&!/ficção|fictíci/i.test(plan.description))plan.description=`Ficção de terror analógico. ${plan.description}`.trim();if(analog){const tags=Array.isArray(plan.hashtags)?plan.hashtags:[];plan.hashtags=[...new Set([...tags,'#TerrorAnalogico','#AnalogHorror','#Ficcao'])].slice(0,8)}const b=plan.analog_bible||{},continuity=analog?`SAME TAPE — format: ${b.format}; year: ${b.year}; organization: ${b.organization}; location: ${b.location}; recurring subject: ${b.recurring_subject}; threat: ${b.threat}; immutable visual rules: ${b.visual_rules}; required ending: ${b.ending}. Red, black and gray 4:3 CRT archive; preserve every recurring design element.`:'';plan.visual_context=String(analog?continuity:(plan.visual_context||(real?'true historical mystery documentary, cinematic restrained lighting, period accurate locations':'psychological horror, cinematic low key lighting, deep shadows, restrained color palette'))).slice(0,1400);const seen=new Set();
  plan.scenes=plan.scenes.slice(0,10).map((s,i)=>{const narration=String(s.narration||'').trim(),rawDesc=String(s.visual_description||'').trim(),desc=String(analog?`${continuity} CURRENT FRAME ${i+1}: ${rawDesc}`:rawDesc).slice(0,1400);let primary=compact(s.visual_query||rawDesc||narration,16),backup=compact(s.visual_query_backup||primary,16);primary=`${primary} ${analog?compact(`${b.organization} ${b.location} ${b.recurring_subject}`,10):''} ${visualAnchor}`.replace(/\s+/g,' ').slice(0,260);backup=`${backup} ${analog?compact(`${b.organization} ${b.location} ${b.recurring_subject}`,10):'alternate angle'} ${visualAnchor}`.replace(/\s+/g,' ').slice(0,260);if(seen.has(primary.toLowerCase()))primary=`${compact(rawDesc,12)} ${real?'documented case':'suspense'} scene ${i+1} ${visualAnchor}`.slice(0,260);seen.add(primary.toLowerCase());let recommended=analog?'image':s.recommended_media==='video'?'video':'image';if(!analog&&mediaMode==='photos')recommended='image';if(!analog&&mediaMode==='videos')recommended='video';return{beat:String(s.beat||`Cena ${i+1}`).slice(0,100),narration,visual_description:desc,visual_query:primary,visual_query_backup:backup,recommended_media:recommended}});
  return res.status(200).json({plan,preset:real?'Terror Real':analog?'Terror Analógico':'Terror e Suspense'});
 }catch(error){console.error('horror-plan',error);return res.status(500).json({error:'Não foi possível criar a história agora. Tente novamente em alguns instantes.'})}
};
