const { requireAuth } = require('../lib/auth');
const {buildAvoidance,avoidText,targetNarrationWords,minNarrationWords,maxNarrationWords,narrationWordCount,tooSimilar,pickUnused}=require('../lib/content-freshness');
const illustratedPlanHandler=require('../lib/illustrated-plan-handler');
const BIBLICAL_STORY_POOL=['A criação e a queda em Gênesis 1–3','Noé e o dilúvio em Gênesis 6–9','A chamada de Abraão em Gênesis 12','Abraão e Isaque no monte Moriá em Gênesis 22','José é vendido pelos irmãos e chega ao Egito em Gênesis 37–50','Moisés e a sarça ardente em Êxodo 3','A travessia do Mar Vermelho em Êxodo 14','O maná no deserto em Êxodo 16','A queda das muralhas de Jericó em Josué 6','Gideão e os trezentos em Juízes 6–7','Sansão e Dalila em Juízes 16','Rute e Boaz no livro de Rute','Samuel ouve a voz de Deus em 1 Samuel 3','Davi e Golias em 1 Samuel 17','Elias no monte Carmelo em 1 Reis 18','Ester intercede por seu povo','Jó permanece fiel em meio ao sofrimento','Jonas e Nínive','Daniel na cova dos leões','Neemias reconstrói os muros de Jerusalém','Jesus acalma a tempestade em Marcos 4','A multiplicação dos pães e peixes em João 6','A mulher samaritana em João 4','A ressurreição de Lázaro em João 11','O filho pródigo em Lucas 15','O bom samaritano em Lucas 10','A conversão de Paulo em Atos 9','Paulo e Silas na prisão em Atos 16','O naufrágio de Paulo em Atos 27','Pentecostes em Atos 2'];
const DEVOTIONAL_POOL=[{ref:'Salmo 23:1',theme:'confiança no cuidado de Deus'},{ref:'Isaías 41:10',theme:'coragem quando o medo tenta dominar'},{ref:'Filipenses 4:6-7',theme:'oração e paz em meio à ansiedade'},{ref:'Provérbios 3:5-6',theme:'confiar em Deus sem entender todo o caminho'},{ref:'Romanos 8:28',theme:'esperança em fases difíceis'},{ref:'Mateus 11:28-30',theme:'descanso em Cristo'},{ref:'Salmo 46:1',theme:'Deus como refúgio e força'},{ref:'Lamentações 3:22-23',theme:'misericórdia e recomeço'},{ref:'Josué 1:9',theme:'força e coragem'},{ref:'2 Coríntios 12:9',theme:'a graça de Deus em nossa fraqueza'},{ref:'1 Pedro 5:7',theme:'entregar preocupações a Deus'},{ref:'João 14:27',theme:'a paz de Cristo'},{ref:'Gálatas 6:9',theme:'não desistir de fazer o bem'},{ref:'Hebreus 11:1',theme:'fé e confiança'},{ref:'Salmo 121:1-2',theme:'de onde vem o socorro'},{ref:'Mateus 6:33',theme:'priorizar o Reino de Deus'}];
const UNKNOWN_FACT_POOL=['A inundação de melaço de Boston em 1919','O desastre do lago Nyos nos Camarões em 1986','A Operação Mincemeat durante a Segunda Guerra Mundial','Stanislav Petrov e o falso alerta nuclear de 1983','Violet Jessop, sobrevivente do Titanic, Britannic e Olympic','Tsutomu Yamaguchi, sobrevivente reconhecido de Hiroshima e Nagasaki','A explosão de Halifax em 1917','As trabalhadoras conhecidas como Radium Girls','A epidemia de riso de Tanganica em 1962','A erupção do Krakatoa e suas ondas de choque em 1883','O ano sem verão de 1816','O desastre aéreo de Tenerife em 1977','A missão de resgate do Apollo 13','O acidente nuclear de Palomares em 1966','A descoberta acidental da penicilina por Alexander Fleming','A descoberta dos guerreiros de terracota por agricultores em 1974','A mensagem de Arecibo de 1974','O computador mecânico conhecido como Mecanismo de Anticítera','O incêndio subterrâneo de Centralia, Pensilvânia','A tempestade solar do Evento Carrington de 1859','A Grande Nevasca do Irã em 1972','O terremoto que fez o Mississippi correr temporariamente ao contrário em 1812','A história documentada do náufrago Poon Lim','Juliane Koepcke e a sobrevivência na Amazônia em 1971','A trégua de Natal de 1914','O desastre ferroviário da ponte Tay em 1879','A evacuação marítima de Manhattan em 11 de setembro de 2001','A biblioteca escondida de Dunhuang e sua descoberta em 1900','O experimento de longa duração da gota de piche','A cidade de Pripyat evacuada após Chernobyl'];
const PRESETS={biblical:{label:'Histórias bíblicas',subject:'histórias bíblicas conhecidas do Antigo e Novo Testamento',context:'Oriente Médio e Mediterrâneo antigos, roupas e ambientes historicamente plausíveis, sem objetos modernos.',anchor:'ancient middle east historical reenactment simple clothing'},devotional:{label:'Devocional bíblico',subject:'devocionais bíblicos curtos baseados em um texto específico',context:'reflexão bíblica simples e aplicação prática; imagens concretas ligadas a cada frase, evitando clichês repetidos.',anchor:'natural human moment cinematic documentary'},mysteries:{label:'Mistérios e curiosidades',subject:'mistérios históricos e fatos intrigantes sem inventar informações',context:'visual documental e investigativo coerente com o caso.',anchor:'mystery documentary investigation'},ancient:{label:'História antiga',subject:'eventos, personagens e civilizações antigas',context:'reconstituição histórica compatível com época e local.',anchor:'ancient civilization historical reenactment'},motivation:{label:'Motivacional',subject:'superação, disciplina, foco e mudança de vida',context:'ações humanas concretas de treino, estudo, trabalho ou conquista.',anchor:'human achievement cinematic documentary'},science:{label:'Ciência e espaço',subject:'curiosidades científicas e do universo explicadas corretamente',context:'visual científico e documental, sem ficção quando o assunto for ciência real.',anchor:'science documentary realistic'},'true-stories':{label:'Histórias reais',subject:'histórias reais documentadas com começo, conflito e desfecho',context:'mini-documentário coerente com época e local.',anchor:'true story documentary authentic'},'unknown-facts':{label:'Fatos reais desconhecidos',subject:'acontecimentos reais, documentados, surpreendentes e pouco conhecidos de diferentes épocas, países e áreas',context:'mini-documentário investigativo fiel ao local e à época; destaque o detalhe mais inacreditável sem sensacionalismo falso.',anchor:'little known documented real event investigative documentary accurate period'},'life-lessons':{label:'Lição de vida',subject:'histórias curtas com escolhas, consequências e reflexão final',context:'cenas humanas emocionais e coerentes.',anchor:'emotional human story cinematic'},animals:{label:'Natureza e animais',subject:'comportamentos e curiosidades de animais',context:'espécie, habitat e comportamento corretos.',anchor:'wildlife nature documentary'}};
const RELIGIOUS_RX=/\b(jesus|cristo|christ|messias|messiah|bíblia|bible|bíblic|biblic|deus|god|evangelho|gospel|batismo|baptism|oração|prayer|igreja|church|apóstol|apostle|discípul|disciple|salmo|gênesis|genesis|mateus|marcos|lucas|joão|john|atos|romanos|coríntios|hebreus|noé|noah|abraão|abraham|moisés|moses|davi|david|daniel|jonas|jonah|paulo|paul|pedro|peter|pentecost)\b/i;
const JESUS_RX=/\b(jesus|cristo|christ|messias|messiah)\b/i;
const BLOCKED_RX=/\b(catholic|católico|católica|catolicismo|cathedral|catedral|pope|papa|papal|rosary|terço|crucifix|crucifixo|statue|estátua|saint|santo|santa|virgin mary|virgem maria|madonna|marian|mariana|mass|missa|monstrance|ostensório|basilica|basílica|islam|islã|islão|islamic|islâmico|islâmica|muslim|muçulmano|muçulmana|mosque|mesquita|quran|corão|koran|mecca|meca|medina|ramadan|minaret|minarete|imam|candomblé|candomble|umbanda|orixá|orixa|orisha|terreiro|pombagira|pomba gira|iemanjá|iemanja|ogum|oxum|oxóssi|oxossi|xangô|xango|iansã|iansa|obaluaiê|obaluae)\b/i;
function compact(v,max=16){return String(v||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean).slice(0,max).join(' ')}
function cleanBlocked(v){return String(v||'').replace(new RegExp(BLOCKED_RX.source,'gi'),' ').replace(/\b(no|without|sem)\b/gi,' ').replace(/\s+/g,' ').trim()}
function extractJson(text){const raw=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const m=raw.match(/\{[\s\S]*\}/);if(!m)throw Error('Não foi possível criar um roteiro válido.');return JSON.parse(m[0])}
function normalizeEvidence(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim()}
function numericClaimsSupported(plan,corpus){const source=normalizeEvidence(corpus),numbers=(plan?.scenes||[]).flatMap(s=>String(s.narration||'').match(/\b\d+(?:[.,]\d+)?\b/g)||[]);return numbers.every(n=>source.includes(normalizeEvidence(n)))}
async function factualSources(query){const headers={'User-Agent':'ShortCloudStudio/1.0 factual-grounding'},searchQuery=String(query||'').replace(/\s+durante\s+.*$/i,'').replace(/\s+em\s+(?:1\d{3}|20\d{2}).*$/i,'').trim(),searchParams=new URLSearchParams({action:'query',list:'search',srsearch:searchQuery.slice(0,180),srnamespace:'0',srlimit:'2',format:'json',formatversion:'2',origin:'*'}),searchResponse=await fetch(`https://pt.wikipedia.org/w/api.php?${searchParams}`,{headers});if(!searchResponse.ok)throw Error('Fonte factual indisponível');const search=await searchResponse.json(),titles=(search?.query?.search||[]).map(x=>x.title).filter(Boolean).slice(0,2);if(!titles.length)throw Error('Não encontrei fonte documental suficiente para este assunto.');const pages=await Promise.all(titles.map(async title=>{const params=new URLSearchParams({action:'query',titles:title,prop:'extracts|info',explaintext:'1',exsectionformat:'plain',inprop:'url',redirects:'1',format:'json',formatversion:'2',origin:'*'}),response=await fetch(`https://pt.wikipedia.org/w/api.php?${params}`,{headers});if(!response.ok)return null;const data=await response.json();return(data?.query?.pages||[])[0]||null})),sources=pages.filter(x=>String(x?.extract||'').length>=500).slice(0,1).map(x=>({title:String(x.title||''),url:String(x.fullurl||`https://pt.wikipedia.org/?curid=${x.pageid}`),text:String(x.extract||'').slice(0,6500)}));if(!sources.length)throw Error('Não encontrei fonte documental suficiente para este assunto.');return sources}
function retrySeconds(data){const text=String(data?.error?.message||'');const m=text.match(/try again in\s+([0-9.]+)s/i);return Math.max(2,Math.min(25,Math.ceil(Number(m?.[1]||3))))}
async function askModel(key,model,prompt,temp){const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:temp,max_completion_tokens:4400,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});const data=await response.json();return{response,data}}
async function ask(key,model,prompt,temp){let{response,data}=await askModel(key,model,prompt,temp);if(response.ok)return extractJson(data.choices?.[0]?.message?.content||'');const fallback=process.env.GROQ_FALLBACK_MODEL||'llama-3.3-70b-versatile';if(fallback!==model){const second=await askModel(key,fallback,prompt,temp);response=second.response;data=second.data;if(response.ok)return extractJson(data.choices?.[0]?.message?.content||'')}if(response.status===429){const e=Error('rate');e.rate=true;e.retry=retrySeconds(data);throw e}throw Error('Não foi possível criar o roteiro agora.')}
module.exports=async function handler(req,res){
 if(req.query?.__sc_route==='illustrated-plan')return illustratedPlanHandler(req,res);
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 try{
  const key=process.env.GROQ_API_KEY;if(!key)return res.status(500).json({error:'Serviço de criação indisponível.'});
  const presetKey=String(req.body?.presetKey||''),preset=PRESETS[presetKey]||null,topic=String(req.body?.topic||'').trim();if(!topic&&!preset)return res.status(400).json({error:'Informe o tema ou escolha uma categoria.'});if(topic&&BLOCKED_RX.test(topic))return res.status(400).json({error:'Esse tipo de conteúdo religioso não faz parte da proposta deste Studio.'});
  const duration=Math.min(70,Math.max(60,Number(req.body?.duration||65))),tone=String(req.body?.tone||'cinematic'),visualStyle=['realistic','cartoon'].includes(req.body?.visualStyle)?req.body.visualStyle:'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid',voiceSpeed=['default','fast','veryfast'].includes(req.body?.voiceSpeed)?req.body.voiceSpeed:'default';
  const sceneCount=duration<=60?8:duration>=70?10:9,targetWords=targetNarrationWords(duration,voiceSpeed),minWords=minNarrationWords(duration,voiceSpeed),maxWords=maxNarrationWords(duration,voiceSpeed),religious=presetKey==='biblical'||presetKey==='devotional'||RELIGIOUS_RX.test(topic),avoid=await buildAvoidance(req.body);
  const unknownCase=presetKey==='unknown-facts'?(topic||pickUnused(UNKNOWN_FACT_POOL,avoid,x=>x)):'';
  const subject=topic?`ASSUNTO OBRIGATÓRIO DO USUÁRIO: ${topic}. Mantenha esse assunto, mas use um recorte, gancho, sequência e conclusão diferentes dos conteúdos recentes.`:presetKey==='biblical'?`HISTÓRIA BÍBLICA OBRIGATÓRIA: ${pickUnused(BIBLICAL_STORY_POOL,avoid,x=>x)}. Conte exatamente esta história, com um recorte diferente das últimas criações.`:presetKey==='devotional'?(()=>{const d=pickUnused(DEVOTIONAL_POOL,avoid,x=>`${x.ref} ${x.theme}`);return `DEVOCIONAL OBRIGATÓRIO: ${d.ref}, sobre ${d.theme}. Use aplicação e exemplos diferentes dos últimos roteiros.`})():presetKey==='unknown-facts'?`FATO REAL OBRIGATÓRIO: ${unknownCase}. Use exclusivamente o material documental fornecido.`:`Escolha um assunto específico, novo e forte dentro de ${preset.subject}.`;
  const sources=presetKey==='unknown-facts'?await factualSources(unknownCase):[],sourceCorpus=sources.map(x=>x.text).join('\n'),sourceBlock=sources.map((x,i)=>`FONTE ${i+1}: ${x.title}\nURL: ${x.url}\nCONTEÚDO DOCUMENTAL:\n${x.text}`).join('\n\n');
  const religiousRules=religious?`\nDIREÇÃO RELIGIOSA: perspectiva evangélica/protestante, bíblica e cristocêntrica. Não inclua símbolos, rituais, objetos ou arquitetura religiosa fora da proposta do Studio. Não escreva termos proibidos dentro de visual_query, nem mesmo como negação. Use descrições positivas e concretas: ação, local, época, objetos comuns, paisagem, roupa e iluminação.\n`:'';
  const jesusRules=religious&&JESUS_RX.test(topic||subject)?`\nVISUAL REALISTA DE JESUS: nunca peça rosto/corpo fotorealista identificável representando Jesus. Mostre a cena de forma indireta por ambiente, discípulos, multidão, água, estrada, mãos, túmulo vazio ou paisagem.\n`:'';
  const freshness=`\nVARIEDADE OBRIGATÓRIA:\n- Cada nova criação deve trazer conteúdo realmente diferente, mas continuar fiel à categoria escolhida.\n- Não repita assunto, título, protagonista, caso, abertura, ordem narrativa, exemplos ou conclusão das criações recentes abaixo.\n- Se o usuário informou um assunto específico, preserve o assunto e mude o recorte e a construção narrativa.\nCONTEÚDOS RECENTES A EVITAR:\n${avoidText(avoid)}\n`;
  const factualRules=presetKey==='unknown-facts'?`\nRIGOR FACTUAL OBRIGATÓRIO:\n- Use EXCLUSIVAMENTE afirmações sustentadas pelo conteúdo documental abaixo. Seu conhecimento interno não é fonte.\n- Não crie falas, pensamentos, cenas privadas, motivações, números, datas, nomes ou consequências ausentes da fonte.\n- Diferencie fato confirmado, alegação e hipótese exatamente como a fonte diferencia.\n- Se um detalhe não estiver na fonte, omita-o. O impacto deve vir do fato documentado.\n- Você pode parafrasear para uma narração natural, mas não pode ampliar o sentido nem completar lacunas.\n\n${sourceBlock}\n`:'';
  const basePrompt=`Crie roteiro e storyboard para UM Short vertical em português do Brasil.\n${subject}\nCATEGORIA: ${preset?.label||'Personalizado'} | DURAÇÃO: ${duration}s | TOM: ${tone} | VISUAL: ${visualStyle} | MÍDIA: ${mediaMode}\nCONTEXTO: ${preset?.context||'Siga exatamente o assunto do usuário.'}\n${freshness}${religiousRules}${jesusRules}${factualRules}\nNARRAÇÃO:\n- O texto narrado completo DEVE ter entre ${minWords} e ${maxWords} palavras, com alvo de ${targetWords}. Não entregue menos que ${minWords}.\n- Distribua o texto entre ${sceneCount} cenas; não faça cenas de uma única frase curta.\n- Gancho forte, progressão, clímax e conclusão.\n- Português brasileiro natural para voz neural: frases fluidas, pontuação respirável, sem estilo de lista.\n- Não invente fatos quando a categoria for factual ou histórica.\nDIREÇÃO VISUAL PROFISSIONAL:\n- visual_context deve ser uma bíblia visual curta EM INGLÊS para o vídeo inteiro: época/local, luz, paleta, textura cinematográfica, aparência consistente de personagens recorrentes e linguagem de câmera.\n- Cada visual_description deve mostrar uma ação VISÍVEL específica daquela frase, não uma metáfora genérica.\n- Cada visual_query e visual_query_backup deve estar EM INGLÊS, 8 a 16 palavras, positiva e pesquisável.\n- Não repita a mesma busca, o mesmo objeto ou o mesmo clichê em cenas diferentes.\n- Preserve continuidade de roupas, idade aproximada e características dos personagens recorrentes.\n- Para cenas únicas/históricas/nomeadas em que mídia pronta provavelmente ficará errada, recommended_media deve ser image.\n- Use video principalmente quando a ação for genérica e realmente se beneficiar de movimento real.\n- Em modo photos use sempre image; em videos use sempre video.\nRetorne SOMENTE JSON válido com: title, summary, description, hashtags, niche_key, visual_context e scenes. Cada scene: beat, narration, visual_description, visual_query, visual_query_backup, recommended_media.`;
  const model=process.env.GROQ_MODEL||'qwen/qwen3.8-27b';let plan=null;
  for(let attempt=0;attempt<2;attempt++){
    const repair=attempt?`\nA tentativa anterior ficou curta ou parecida demais. Refaça do zero, com pelo menos ${minWords} palavras narradas e um título/ângulo diferente.`:'';
    try{plan=await ask(key,model,basePrompt+repair,religious?0.38:0.56)}catch(e){if(e.rate)return res.status(429).json({error:'Muita atividade no momento. A tentativa será repetida automaticamente.',retryAfterSeconds:e.retry});throw e}
    const grounded=presetKey!=='unknown-facts'||numericClaimsSupported(plan,sourceCorpus);
    if(Array.isArray(plan.scenes)&&plan.scenes.length>=6&&narrationWordCount(plan)>=minWords&&grounded&&(topic||!tooSimilar(plan.title,avoid)))break;
    plan=null;
  }
  if(presetKey==='unknown-facts'&&!plan)return res.status(422).json({error:'O roteiro tentou usar uma data ou número ausente da fonte. Tente novamente ou informe outro fato real.'});
  if(!plan||!Array.isArray(plan.scenes)||plan.scenes.length<6||narrationWordCount(plan)<minWords)throw Error('O roteiro retornou curto demais.');
  plan.niche_key=presetKey||'custom';if(sources.length){plan.factual_sources=sources.map(({title,url})=>({title,url}));plan.description=`${String(plan.description||'').trim()}\n\nFontes consultadas: ${sources.map(x=>`${x.title} — ${x.url}`).join(' | ')}`.trim().slice(0,1800)}plan.visual_context=cleanBlocked(String(plan.visual_context||preset?.context||'')).slice(0,900);const anchor=preset?.anchor||'',seen=new Set();
  plan.scenes=plan.scenes.slice(0,10).map((s,i)=>{const narration=String(s.narration||'').trim(),desc=cleanBlocked(String(s.visual_description||'').trim()).slice(0,900);let vq=cleanBlocked(compact(s.visual_query,16)),vb=cleanBlocked(compact(s.visual_query_backup||s.visual_query,16));if(religious&&JESUS_RX.test(`${vq} ${desc}`)){vq=vq.replace(new RegExp(JESUS_RX.source,'gi'),' ').replace(/\s+/g,' ').trim();vb=vb.replace(new RegExp(JESUS_RX.source,'gi'),' ').replace(/\s+/g,' ').trim()}if(!vq)vq=compact(desc||narration,14);if(!vb)vb=`${vq} alternate angle`;let primary=`${vq} ${anchor}`.trim().replace(/\s+/g,' ').slice(0,210),backup=`${vb} ${anchor}`.trim().replace(/\s+/g,' ').slice(0,210);if(seen.has(primary.toLowerCase()))primary=`${compact(desc,12)} ${anchor} scene ${i+1}`.trim().slice(0,210);seen.add(primary.toLowerCase());let recommended=s.recommended_media==='video'?'video':'image';if(mediaMode==='photos')recommended='image';if(mediaMode==='videos')recommended='video';return{beat:String(s.beat||`Cena ${i+1}`).slice(0,100),narration,visual_description:desc,visual_query:primary,visual_query_backup:backup,recommended_media:recommended}});
  return res.status(200).json({plan,preset:preset?.label||null});
 }catch(error){console.error(error);if(/Fonte factual|fonte documental/i.test(String(error?.message||'')))return res.status(422).json({error:'Não encontrei documentação suficiente para comprovar esse assunto. Tente outro fato real.'});return res.status(500).json({error:'Não foi possível criar o roteiro agora. Tente novamente em alguns instantes.'})}
};
