const { requireAuth } = require('../lib/auth');

const BIBLICAL_STORY_POOL=[
'A criação e a queda em Gênesis 1–3','Noé e o dilúvio em Gênesis 6–9','A chamada de Abraão em Gênesis 12','Abraão e Isaque no monte Moriá em Gênesis 22','Jacó luta com Deus em Gênesis 32','José é vendido pelos irmãos e chega ao Egito em Gênesis 37–50','Moisés e a sarça ardente em Êxodo 3','As dez pragas do Egito em Êxodo 7–12','A travessia do Mar Vermelho em Êxodo 14','O maná no deserto em Êxodo 16','A queda das muralhas de Jericó em Josué 6','Gideão e os trezentos em Juízes 6–7','Sansão e Dalila em Juízes 16','Rute e Boaz no livro de Rute','Ana ora por um filho em 1 Samuel 1','Samuel ouve a voz de Deus em 1 Samuel 3','Davi e Golias em 1 Samuel 17','Davi poupa a vida de Saul em 1 Samuel 24','Salomão pede sabedoria em 1 Reis 3','Elias no monte Carmelo em 1 Reis 18','Elias e a viúva de Sarepta em 1 Reis 17','Naamã é curado em 2 Reis 5','Ester intercede por seu povo','Jó permanece fiel em meio ao sofrimento','Jonas e Nínive','Daniel na cova dos leões','Sadraque, Mesaque e Abede-Nego na fornalha','Neemias reconstrói os muros de Jerusalém','O nascimento de Jesus em Lucas 1–2','Jesus acalma a tempestade em Marcos 4','A multiplicação dos pães e peixes em João 6','A mulher samaritana em João 4','A cura do paralítico em Marcos 2','A ressurreição de Lázaro em João 11','Zaqueu encontra Jesus em Lucas 19','O filho pródigo em Lucas 15','O bom samaritano em Lucas 10','Pedro anda sobre as águas em Mateus 14','A conversão de Paulo em Atos 9','Paulo e Silas na prisão em Atos 16','O naufrágio de Paulo em Atos 27','Pentecostes em Atos 2','Estêvão permanece fiel até o fim em Atos 6–7'];
const DEVOTIONAL_POOL=[
{ref:'Salmo 23:1',theme:'confiança no cuidado de Deus'},{ref:'Isaías 41:10',theme:'coragem quando o medo tenta dominar'},{ref:'Filipenses 4:6-7',theme:'oração e paz em meio à ansiedade'},{ref:'Provérbios 3:5-6',theme:'confiar em Deus sem entender todo o caminho'},{ref:'Romanos 8:28',theme:'esperança em fases difíceis'},{ref:'Mateus 11:28-30',theme:'descanso em Cristo'},{ref:'Salmo 46:1',theme:'Deus como refúgio e força'},{ref:'Lamentações 3:22-23',theme:'misericórdia e recomeço'},{ref:'Josué 1:9',theme:'força e coragem'},{ref:'2 Coríntios 12:9',theme:'a graça de Deus em nossa fraqueza'},{ref:'Salmo 37:5',theme:'entregar caminhos ao Senhor'},{ref:'1 Pedro 5:7',theme:'entregar preocupações a Deus'},{ref:'João 14:27',theme:'a paz de Cristo'},{ref:'Gálatas 6:9',theme:'não desistir de fazer o bem'},{ref:'Hebreus 11:1',theme:'fé e confiança'},{ref:'Salmo 121:1-2',theme:'de onde vem o socorro'},{ref:'Tiago 1:5',theme:'buscar sabedoria em Deus'},{ref:'Mateus 6:33',theme:'priorizar o Reino de Deus'}];

const PRESETS={
 biblical:{label:'Histórias bíblicas',subject:'histórias bíblicas conhecidas do Antigo e Novo Testamento',context:'Oriente Médio antigo, roupas e ambientes historicamente plausíveis; sem objetos modernos ou estética medieval europeia.',anchor:'ancient biblical middle east historical'},
 devotional:{label:'Devocional bíblico',subject:'devocionais bíblicos curtos baseados em um texto específico',context:'reflexão bíblica simples, fiel ao contexto, com aplicação prática.',anchor:'biblical devotional scripture peaceful'},
 mysteries:{label:'Mistérios e curiosidades',subject:'mistérios históricos e fatos intrigantes sem inventar informações',context:'visual documental e investigativo coerente com o caso.',anchor:'mystery documentary investigation'},
 ancient:{label:'História antiga',subject:'eventos, personagens e civilizações antigas',context:'reconstituição histórica compatível com época e local.',anchor:'ancient civilization historical archaeology'},
 motivation:{label:'Motivacional',subject:'superação, disciplina, foco e mudança de vida',context:'ações humanas concretas de treino, estudo, trabalho ou conquista.',anchor:'motivational human achievement cinematic'},
 science:{label:'Ciência e espaço',subject:'curiosidades científicas e do universo explicadas corretamente',context:'visual científico e documental, sem ficção quando o assunto for ciência real.',anchor:'science documentary space astronomy'},
 'true-stories':{label:'Histórias reais',subject:'histórias reais documentadas com começo, conflito e desfecho',context:'mini-documentário coerente com época e local.',anchor:'true story documentary historical'},
 'life-lessons':{label:'Lição de vida',subject:'histórias curtas com escolhas, consequências e reflexão final',context:'cenas humanas emocionais e coerentes.',anchor:'emotional human story cinematic'},
 animals:{label:'Natureza e animais',subject:'comportamentos e curiosidades de animais',context:'espécie, habitat e comportamento corretos.',anchor:'wildlife nature documentary'}
};

const CARTOON_STYLES={interdimensional:'2D sci-fi surreal','paper-cut':'recortes 2D com profundidade','retro-surreal':'2D retro surreal','classic-2d':'animação 2D clássica e polida',comic:'HQ cinematográfica'};
const RELIGIOUS_RX=/\b(jesus|cristo|christ|messias|messiah|bíblia|bible|bíblic|biblic|deus|god|evangelho|gospel|batismo|baptism|oração|prayer|igreja|church|apóstol|apostle|discípul|disciple|salmo|gênesis|genesis|mateus|marcos|lucas|joão|john|atos|romanos|coríntios|hebreus)\b/i;
const JESUS_RX=/\b(jesus|cristo|christ|messias|messiah)\b/i;
function random(list){return list[Math.floor(Math.random()*list.length)]}
function compact(v,max=12){return String(v||'').trim().split(/\s+/).filter(Boolean).slice(0,max).join(' ')}
function extractJson(text){const raw=String(text||'').replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/i,'');const m=raw.match(/\{[\s\S]*\}/);if(!m)throw Error('Não foi possível criar um roteiro válido.');return JSON.parse(m[0])}

module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 try{
  const key=process.env.GROQ_API_KEY;if(!key)return res.status(500).json({error:'Serviço de criação indisponível.'});
  const presetKey=String(req.body?.presetKey||''),preset=PRESETS[presetKey]||null,topic=String(req.body?.topic||'').trim();if(!topic&&!preset)return res.status(400).json({error:'Informe o tema ou escolha uma categoria.'});
  const duration=Math.min(70,Math.max(60,Number(req.body?.duration||65))),tone=String(req.body?.tone||'cinematic'),visualStyle=['realistic','cartoon'].includes(req.body?.visualStyle)?req.body.visualStyle:'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid';
  const sceneCount=duration<=60?8:duration>=70?10:9,targetWords=Math.round(duration*2.25),religious=presetKey==='biblical'||presetKey==='devotional'||RELIGIOUS_RX.test(topic);
  const subject=topic?`ASSUNTO OBRIGATÓRIO DO USUÁRIO: ${topic}. A categoria define apenas a forma de contar; não troque o assunto.`:presetKey==='biblical'?`HISTÓRIA BÍBLICA ALEATÓRIA OBRIGATÓRIA: ${random(BIBLICAL_STORY_POOL)}. Conte exatamente esta história.`:presetKey==='devotional'?(()=>{const d=random(DEVOTIONAL_POOL);return `DEVOCIONAL OBRIGATÓRIO: ${d.ref}, sobre ${d.theme}.`})():`Escolha um assunto específico e forte dentro de ${preset.subject}.`;
  const evangelicalRules=religious?`\nREGRAS PARA TODO CONTEÚDO RELIGIOSO:\n- Perspectiva evangélica/protestante, bíblica e cristocêntrica.\n- Baseie ensino e aplicação no texto bíblico; não use tradição católica como autoridade doutrinária.\n- Não inclua devoção a santos ou Maria, rosário/terço, missa, papa, purgatório, intercessão de santos, imagens de veneração ou linguagem sacramental católica.\n- Mantenha respeito ao tratar outras tradições; simplesmente não use esses elementos como parte do conteúdo.\n- Visualmente, não use iconografia católica: rosário, crucifixo, estátuas de santos, imagens marianas, altares ornamentados ou vestes clericais católicas.\n- Uma cruz simples, Bíblia, oração, congregação, natureza e ambientes bíblicos podem ser usados quando coerentes.\n`:'';
  const jesusVisual=religious&&JESUS_RX.test(topic||subject)?`\nREGRA ESPECIAL SOBRE JESUS NO MODO REALISTA:\n- NÃO solicite retrato, ator, rosto ou corpo fotorealista identificável representando Jesus.\n- Mostre a cena indiretamente: ambiente bíblico, discípulos, multidão, água, barco, estrada, mãos, túmulo vazio, paisagem ou composição simbólica.\n- Em desenho/ilustração, mantenha representação respeitosa e não-católica.\n`:'';
  const prompt=`Você cria roteiro e storyboard para Short vertical em português do Brasil.\n${subject}\nCATEGORIA: ${preset?.label||'Personalizado'}\nDURAÇÃO: ${duration}s. TOM: ${tone}. VISUAL: ${visualStyle}. MÍDIA: ${mediaMode}.\nCONTEXTO: ${preset?.context||'Siga exatamente o assunto do usuário.'}\n${evangelicalRules}${jesusVisual}\nCrie cerca de ${targetWords} palavras em ${sceneCount} cenas. Tenha gancho, progressão, clímax e conclusão. Não invente fatos religiosos, históricos ou científicos.\nPara cada cena, narration deve ser a fala final; visual_description deve dizer exatamente o que aparece; visual_query e visual_query_backup devem estar em inglês e ser pesquisáveis, coerentes com época/local/ação, sem texto na imagem. recommended_media deve ser image ou video.\nSe o conteúdo for religioso, todas as queries também devem seguir a estética evangélica/protestante e excluir iconografia católica. Se a cena envolver Jesus e o visual for realista, as queries devem descrever o ambiente/cena de modo indireto, sem pessoa identificável representando Jesus.\nRetorne SOMENTE JSON: {"title":"...","summary":"...","description":"...","hashtags":["#..."],"niche_key":"${presetKey||'custom'}","visual_context":"...","scenes":[{"beat":"...","narration":"...","visual_description":"...","visual_query":"...","visual_query_backup":"...","recommended_media":"image"}]}`;
  const model=process.env.GROQ_MODEL||'qwen/qwen3.8-27b';const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,temperature:religious?0.42:0.48,max_completion_tokens:4600,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});const data=await response.json();if(!response.ok)throw Error(data?.error?.message||'Não foi possível criar o roteiro.');
  const plan=extractJson(data.choices?.[0]?.message?.content||'');if(!Array.isArray(plan.scenes)||plan.scenes.length<6)throw Error('O roteiro retornou poucas cenas.');plan.niche_key=presetKey||'custom';plan.visual_context=String(plan.visual_context||preset?.context||'').slice(0,700);const anchor=preset?.anchor||'';
  plan.scenes=plan.scenes.slice(0,10).map((s,i)=>({beat:String(s.beat||`Cena ${i+1}`).slice(0,100),narration:String(s.narration||'').trim(),visual_description:String(s.visual_description||'').trim(),visual_query:`${anchor} ${compact(s.visual_query,14)}`.trim().slice(0,200),visual_query_backup:`${anchor} ${compact(s.visual_query_backup||s.visual_query,14)}`.trim().slice(0,200),recommended_media:mediaMode==='photos'?'image':mediaMode==='videos'?'video':s.recommended_media==='video'?'video':'image'}));
  return res.status(200).json({plan,model,preset:preset?.label||null});
 }catch(error){console.error(error);return res.status(500).json({error:error.message||'Falha ao criar o roteiro.'})}
};