const { requireAuth } = require('../lib/auth');
const NICHE_HINTS={biblical:'ancient biblical Middle East historically plausible simple clothing and environment',devotional:'biblical devotional atmosphere peaceful natural light scripture-centered context',mysteries:'mystery documentary atmosphere investigation suspense coherent location and objects',ancient:'ancient civilization historically plausible architecture clothing and environment',motivation:'human determination training discipline work study or achievement cinematic realistic scene',science:'science documentary astronomy laboratory space or natural phenomenon scientifically plausible','true-stories':'documentary realism authentic human scene believable location and period details','life-lessons':'emotional human story everyday life reflective cinematic scene',animals:'wildlife documentary correct species natural habitat realistic animal behavior',custom:'coherent cinematic scene matching the description exactly'};
const RELIGIOUS_RX=/\b(jesus|cristo|christ|messias|messiah|bíblia|bible|bíblic|biblic|deus|god|evangelho|gospel|batismo|baptism|oração|prayer|igreja|church|apóstol|apostle|discípul|disciple|salmo|gênesis|genesis|mateus|marcos|lucas|joão|john|atos|romanos|coríntios|hebreus|noé|noah|abraão|abraham|isaque|isaac|jacó|jacob|josé|joseph|moisés|moses|josué|joshua|gideão|gideon|sansão|samson|rute|ruth|samuel|davi|david|salomão|solomon|elias|elijah|naamã|naaman|ester|esther|jó|job|jonas|jonah|daniel|neemias|nehemiah|paulo|paul|pedro|peter|pentecostes|pentecost)\b/i;
const JESUS_RX=/\b(jesus|cristo|christ|messias|messiah)\b/i;
const BLOCKED_RX=/\b(catholic|católico|católica|cathedral|catedral|pope|papa|papal|rosary|terço|crucifix|crucifixo|statue|estátua|saint|santo|santa|virgin mary|virgem maria|madonna|marian|mass|missa|monstrance|ostensório|basilica|basílica|islam|islã|islão|islamic|islâmico|islâmica|muslim|muçulmano|muçulmana|mosque|mesquita|quran|corão|koran|mecca|meca|medina|ramadan|minaret|minarete|imam|candomblé|candomble|umbanda|orixá|orixa|orisha|terreiro|pombagira|pomba gira|iemanjá|iemanja|ogum|oxum|oxóssi|oxossi|xangô|xango|iansã|iansa|obaluaiê|obaluae)\b/gi;
function compact(value,max=14){return String(value||'').trim().replace(/\s+/g,' ').split(' ').slice(0,max).join(' ')}
function clean(value,jesus){let v=String(value||'').replace(BLOCKED_RX,' ');if(jesus)v=v.replace(JESUS_RX,' ')+' ancient Galilee environment disciples crowd landscape';return v.replace(/\b(no|without|sem)\b/gi,' ').replace(/\s+/g,' ').trim()}
function fallback(description,narration,niche,religious,jesus){const hint=NICHE_HINTS[niche]||NICHE_HINTS.custom;let base=compact(description||narration||'cinematic scene',18);if(religious)base=clean(base,jesus);const context=compact(hint,12);if(!religious)return{visual_query:`${base} ${context}`.trim().slice(0,180),visual_query_backup:`${context} ${base}`.trim().slice(0,180)};return{visual_query:`${base||'ancient middle east people'} ${context} simple tunics historical reenactment`.trim().slice(0,180),visual_query_backup:`first century Mediterranean landscape people simple tunics historical reenactment`.slice(0,180)}}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 const description=String(req.body?.visualDescription||'').trim(),narration=String(req.body?.narration||'').trim(),niche=String(req.body?.presetKey||'custom'),visualStyle=req.body?.visualStyle==='cartoon'?'cartoon':'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid';
 if(!description&&!narration)return res.status(400).json({error:'Descreva a cena.'});
 const combined=`${description} ${narration}`,religious=niche==='biblical'||niche==='devotional'||RELIGIOUS_RX.test(combined),jesus=religious&&JESUS_RX.test(combined),safeFallback=fallback(description,narration,niche,religious,jesus),key=process.env.GROQ_API_KEY;
 if(!key)return res.status(200).json({...safeFallback,recommended_media:mediaMode==='videos'?'video':'image'});
 try{
  const hint=NICHE_HINTS[niche]||NICHE_HINTS.custom;
  const religiousRules=religious?`\n- Conteúdo visual exclusivamente evangélico/protestante e bíblico.\n- Não inclua iconografia, rituais, templos ou símbolos católicos, islâmicos ou de religiões afro-brasileiras/de matriz africana.\n- NÃO escreva os nomes desses elementos nas buscas nem mesmo precedidos por "no" ou "without"; use somente descrições positivas do que deve aparecer.\n${jesus&&visualStyle==='realistic'?'- Não peça figura fotorealista identificável de Jesus; descreva ambiente, discípulos, multidão, água, estrada, túmulo, mãos ou paisagem.':''}`:'';
  const prompt=`Transforme a descrição abaixo em duas buscas VISUAIS CURTAS em inglês para encontrar mídia coerente para um Short vertical.\nDESCRIÇÃO: ${description||narration}\nNARRAÇÃO: ${narration}\nNICHO: ${hint}\nESTILO: ${visualStyle==='cartoon'?'illustration/cartoon reference':'realistic stock media'}\nMÍDIA: ${mediaMode}\nRegras:\n- Represente exatamente a cena, com termos alternativos.\n- Priorize pessoas, ação, lugar, época, objetos e clima.\n- Não invente personagens ou épocas.\n- Em conteúdo histórico/bíblico, evite anacronismos.\n- Máximo 14 palavras por busca.${religiousRules}\n- Em hybrid escolha image ou video; em photos use image; em videos use video.\nResponda SOMENTE JSON: {"visual_query":"...","visual_query_backup":"...","recommended_media":"image ou video"}`;
  const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'qwen/qwen3.8-27b',temperature:.12,max_completion_tokens:300,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});
  const data=await response.json();if(!response.ok)throw new Error('temporary');const parsed=JSON.parse(String(data.choices?.[0]?.message?.content||'{}'));
  let primary=clean(compact(parsed.visual_query,14),jesus&&visualStyle==='realistic')||safeFallback.visual_query,backup=clean(compact(parsed.visual_query_backup,14),jesus&&visualStyle==='realistic')||safeFallback.visual_query_backup;if(religious){primary=`${primary} simple tunics historical reenactment`.slice(0,180);backup=`${backup} simple tunics historical reenactment`.slice(0,180)}
  let recommended=parsed.recommended_media==='video'?'video':'image';if(mediaMode==='photos')recommended='image';if(mediaMode==='videos')recommended='video';return res.status(200).json({visual_query:primary,visual_query_backup:backup,recommended_media:recommended});
 }catch(error){console.error('scene-query',error);return res.status(200).json({...safeFallback,recommended_media:mediaMode==='videos'?'video':'image'})}
};
