const { requireAuth } = require('../lib/auth');
const NICHE_HINTS={biblical:'ancient middle east historical reenactment simple clothing authentic environment',devotional:'specific human action natural cinematic documentary lighting',mysteries:'mystery documentary investigation coherent location and objects',ancient:'ancient civilization historically plausible architecture clothing environment',motivation:'human determination training discipline work study achievement realistic',science:'science documentary laboratory space or natural phenomenon scientifically plausible','true-stories':'documentary realism authentic human scene believable location period details','unknown-facts':'little known documented real event accurate period location investigative documentary','life-lessons':'emotional human story everyday life reflective cinematic scene',animals:'wildlife documentary correct species natural habitat realistic behavior',custom:'coherent cinematic scene matching the description exactly'};
const RELIGIOUS_RX=/\b(jesus|cristo|christ|messias|messiah|bíblia|bible|bíblic|biblic|deus|god|evangelho|gospel|batismo|baptism|oração|prayer|igreja|church|apóstol|apostle|discípul|disciple|salmo|gênesis|genesis|mateus|marcos|lucas|joão|john|atos|romanos|coríntios|hebreus|noé|noah|abraão|abraham|isaque|isaac|jacó|jacob|josé|joseph|moisés|moses|josué|joshua|gideão|gideon|sansão|samson|rute|ruth|samuel|davi|david|salomão|solomon|elias|elijah|naamã|naaman|ester|esther|jó|job|jonas|jonah|daniel|neemias|nehemiah|paulo|paul|pedro|peter|pentecostes|pentecost)\b/i;
const JESUS_RX=/\b(jesus|cristo|christ|messias|messiah)\b/i;
const BLOCKED_RX=/\b(catholic|católico|católica|cathedral|catedral|pope|papa|papal|rosary|terço|crucifix|crucifixo|statue|estátua|saint|santo|santa|virgin mary|virgem maria|madonna|marian|mass|missa|monstrance|ostensório|basilica|basílica|islam|islã|islão|islamic|islâmico|islâmica|muslim|muçulmano|muçulmana|mosque|mesquita|quran|corão|koran|mecca|meca|medina|ramadan|minaret|minarete|imam|candomblé|candomble|umbanda|orixá|orixa|orisha|terreiro|pombagira|pomba gira|iemanjá|iemanja|ogum|oxum|oxóssi|oxossi|xangô|xango|iansã|iansa|obaluaiê|obaluae)\b/gi;
function compact(value,max=16){return String(value||'').trim().replace(/\s+/g,' ').split(' ').filter(Boolean).slice(0,max).join(' ')}
function clean(value,jesus=false){let v=String(value||'').replace(BLOCKED_RX,' ');if(jesus)v=v.replace(new RegExp(JESUS_RX.source,'gi'),' ');return v.replace(/\b(no|without|sem)\b/gi,' ').replace(/\s+/g,' ').trim()}
function fallback(description,narration,niche,religious,jesus){const hint=NICHE_HINTS[niche]||NICHE_HINTS.custom;let base=compact(description||narration||'cinematic human scene',18);base=clean(base,jesus);if(!base)base=religious?'ancient people natural environment':'cinematic human scene';return{visual_query:`${base} ${hint}`.replace(/\s+/g,' ').trim().slice(0,210),visual_query_backup:`${compact(base,12)} alternate angle authentic environment ${hint}`.replace(/\s+/g,' ').trim().slice(0,210)}}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 const description=String(req.body?.visualDescription||'').trim(),narration=String(req.body?.narration||'').trim(),niche=String(req.body?.presetKey||'custom'),visualStyle=req.body?.visualStyle==='cartoon'?'cartoon':'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid';
 if(!description&&!narration)return res.status(400).json({error:'Descreva a cena.'});const combined=`${description} ${narration}`;if(BLOCKED_RX.test(combined))return res.status(400).json({error:'Essa descrição contém um contexto religioso fora da proposta do Studio.'});
 const religious=niche==='biblical'||niche==='devotional'||RELIGIOUS_RX.test(combined),jesus=religious&&JESUS_RX.test(combined)&&visualStyle==='realistic',safeFallback=fallback(description,narration,niche,religious,jesus),key=process.env.GROQ_API_KEY;if(!key)return res.status(200).json({...safeFallback,recommended_media:mediaMode==='videos'?'video':'image'});
 try{
  const hint=NICHE_HINTS[niche]||NICHE_HINTS.custom,religiousRules=religious?`\n- Use apenas uma descrição POSITIVA do que deve aparecer; não escreva nomes de religiões, símbolos ou rituais proibidos nem mesmo como negação.\n- Preserve cenário histórico simples e plausível quando for uma cena bíblica.\n${jesus?'- Não peça figura fotorealista identificável de Jesus. Descreva ambiente, outras pessoas, água, estrada, mãos, túmulo ou paisagem de forma indireta.':''}\n`:'';
  const prompt=`Transforme a cena abaixo em duas buscas VISUAIS específicas em inglês para um Short vertical.\nDESCRIÇÃO: ${description||narration}\nNARRAÇÃO: ${narration}\nCONTEXTO: ${hint}\nESTILO: ${visualStyle==='cartoon'?'visual illustration reference':'realistic visual media'}\nMÍDIA: ${mediaMode}\nREGRAS:\n- Represente a ação EXATA da cena; não substitua por nuvens, livro, paisagem ou pessoa genérica se houver algo mais específico.\n- Inclua sujeito, ação, local/época e 1 detalhe visual importante.\n- Use termos positivos e pesquisáveis, entre 8 e 16 palavras.\n- As duas buscas precisam ser diferentes entre si.\n- Não invente personagem nem época.\n${religiousRules}- Em hybrid escolha video somente para ação genérica que realmente se beneficie de movimento; para cena histórica/nomeada/específica prefira image.\n- Em photos use image; em videos use video.\nResponda SOMENTE JSON: {"visual_query":"...","visual_query_backup":"...","recommended_media":"image ou video"}`;
  const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'qwen/qwen3.8-27b',temperature:.12,max_completion_tokens:350,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});const data=await response.json();if(!response.ok)throw new Error('temporary');const parsed=JSON.parse(String(data.choices?.[0]?.message?.content||'{}'));
  let primary=clean(compact(parsed.visual_query,16),jesus)||safeFallback.visual_query,backup=clean(compact(parsed.visual_query_backup,16),jesus)||safeFallback.visual_query_backup;if(primary.toLowerCase()===backup.toLowerCase())backup=`${compact(backup,12)} alternate angle natural environment`;if(religious){primary=`${primary} ${hint}`.replace(/\s+/g,' ').slice(0,210);backup=`${backup} ${hint}`.replace(/\s+/g,' ').slice(0,210)}let recommended=parsed.recommended_media==='video'?'video':'image';if(mediaMode==='photos')recommended='image';if(mediaMode==='videos')recommended='video';return res.status(200).json({visual_query:primary,visual_query_backup:backup,recommended_media:recommended});
 }catch(error){console.error('scene-query',error);return res.status(200).json({...safeFallback,recommended_media:mediaMode==='videos'?'video':'image'})}
};
