const { requireAuth } = require('../lib/auth');
const NICHE_HINTS={biblical:'ancient biblical Middle East, historically plausible clothing and environment, no modern objects, no medieval European armor',devotional:'biblical devotional atmosphere, peaceful natural light, scripture-centered Christian context',mysteries:'mystery documentary atmosphere, investigation, suspense, coherent location and objects',ancient:'ancient civilization, historically plausible architecture, clothing and environment, no modern objects',motivation:'human determination, training, discipline, work, study or achievement, cinematic realistic scene',science:'science documentary, astronomy, laboratory, space or natural phenomenon, scientifically plausible','true-stories':'documentary realism, authentic human scene, believable location and period details','life-lessons':'emotional human story, everyday life, reflective cinematic scene',animals:'wildlife documentary, correct species, natural habitat, realistic animal behavior',custom:'coherent cinematic scene matching the description exactly'};
const RELIGIOUS_RX=/\b(jesus|cristo|christ|messias|messiah|bíblia|bible|bíblic|biblic|deus|god|evangelho|gospel|batismo|baptism|oração|prayer|igreja|church|apóstol|apostle|discípul|disciple|salmo|gênesis|genesis|mateus|marcos|lucas|joão|john|atos|romanos|coríntios|hebreus|noé|noah|abraão|abraham|isaque|isaac|jacó|jacob|josé|joseph|moisés|moses|josué|joshua|gideão|gideon|sansão|samson|rute|ruth|samuel|davi|david|salomão|solomon|elias|elijah|naamã|naaman|ester|esther|jó|job|jonas|jonah|daniel|neemias|nehemiah|paulo|paul|pedro|peter|pentecostes|pentecost)\b/i;
const JESUS_RX=/\b(jesus|cristo|christ|messias|messiah)\b/i;
const CATHOLIC_RX=/\b(catholic|cathedral|pope|papal|rosary|terço|crucifix|crucifixo|statue|estátua|saint|santo|santa|virgin mary|virgem maria|madonna|marian|missa|mass|monstrance|ostensório)\b/gi;
function compact(value,max=14){return String(value||'').trim().replace(/\s+/g,' ').split(' ').slice(0,max).join(' ')}
function religiousClean(value,jesus){let v=String(value||'').replace(CATHOLIC_RX,' ');if(jesus)v=v.replace(JESUS_RX,' ')+' ancient biblical setting disciples crowd landscape symbolic scene';return v.replace(/\s+/g,' ').trim()}
function fallback(description,narration,niche,religious,jesus){const hint=NICHE_HINTS[niche]||NICHE_HINTS.custom;let base=compact(description||narration||'cinematic scene',18);if(religious)base=religiousClean(base,jesus);const context=compact(hint,12);const guard=religious?' evangelical protestant biblical no catholic icons':'';return{visual_query:`${base} ${context}${guard}`.trim().slice(0,180),visual_query_backup:`${context} ${base}${guard}`.trim().slice(0,180)}}
module.exports=async function handler(req,res){
 if(req.method!=='POST')return res.status(405).json({error:'Use POST.'});if(!requireAuth(req,res))return;
 const description=String(req.body?.visualDescription||'').trim(),narration=String(req.body?.narration||'').trim(),niche=String(req.body?.presetKey||'custom'),visualStyle=req.body?.visualStyle==='cartoon'?'cartoon':'realistic',mediaMode=['photos','videos','hybrid'].includes(req.body?.mediaMode)?req.body.mediaMode:'hybrid';
 if(!description&&!narration)return res.status(400).json({error:'Descreva a cena.'});
 const combined=`${description} ${narration}`,religious=niche==='biblical'||niche==='devotional'||RELIGIOUS_RX.test(combined),jesus=religious&&JESUS_RX.test(combined),safeFallback=fallback(description,narration,niche,religious,jesus),key=process.env.GROQ_API_KEY;
 if(!key)return res.status(200).json({...safeFallback,recommended_media:mediaMode==='videos'?'video':'image',source:'local-fallback'});
 try{
  const hint=NICHE_HINTS[niche]||NICHE_HINTS.custom;
  const religiousRules=religious?`\n- Use visual language compatible with evangelical/protestant biblical content.\n- Exclude Catholic iconography such as rosary, saints, Marian statues, ornate crucifixes, papal or mass imagery.\n${jesus&&visualStyle==='realistic'?'- Do not request a photorealistic identifiable Jesus figure. Describe environment, disciples, crowd, water, road, tomb, hands or landscape instead.':''}`:'';
  const prompt=`Transforme a descrição abaixo em duas buscas VISUAIS CURTAS em inglês para encontrar mídia coerente para um Short vertical.\nDESCRIÇÃO: ${description||narration}\nNARRAÇÃO: ${narration}\nNICHO: ${hint}\nESTILO: ${visualStyle==='cartoon'?'illustration/cartoon reference':'realistic stock media'}\nMÍDIA: ${mediaMode}\nRegras:\n- Represente exatamente a cena, com termos alternativos.\n- Priorize pessoas, ação, lugar, época, objetos e clima.\n- Não invente personagens ou épocas.\n- Em conteúdo histórico/bíblico, evite anacronismos.\n- Máximo 14 palavras por busca.${religiousRules}\n- Em hybrid escolha image ou video; em photos use image; em videos use video.\nResponda SOMENTE JSON: {"visual_query":"...","visual_query_backup":"...","recommended_media":"image ou video"}`;
  const response=await fetch('https://api.groq.com/openai/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GROQ_MODEL||'qwen/qwen3.8-27b',temperature:.16,max_completion_tokens:300,response_format:{type:'json_object'},messages:[{role:'user',content:prompt}]})});
  const data=await response.json();if(!response.ok)throw new Error('temporary');const parsed=JSON.parse(String(data.choices?.[0]?.message?.content||'{}'));
  let primary=compact(parsed.visual_query,14)||safeFallback.visual_query,backup=compact(parsed.visual_query_backup,14)||safeFallback.visual_query_backup;
  if(religious){primary=religiousClean(primary,jesus&&visualStyle==='realistic');backup=religiousClean(backup,jesus&&visualStyle==='realistic');primary=`${primary} evangelical protestant biblical`.slice(0,180);backup=`${backup} evangelical protestant biblical`.slice(0,180)}
  let recommended=parsed.recommended_media==='video'?'video':'image';if(mediaMode==='photos')recommended='image';if(mediaMode==='videos')recommended='video';return res.status(200).json({visual_query:primary,visual_query_backup:backup,recommended_media:recommended,source:'generated'});
 }catch(error){console.error('scene-query',error);return res.status(200).json({...safeFallback,recommended_media:mediaMode==='videos'?'video':'image',source:'local-fallback'})}
};